CREATE TABLE "audit_logs" (
	"id" text PRIMARY KEY NOT NULL,
	"acao" text NOT NULL,
	"recurso" text NOT NULL,
	"idrecurso" text,
	"idusuario" text,
	"idempresa" text,
	"metadados" jsonb,
	"criadoem" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "contacorrente" (
	"id" text PRIMARY KEY NOT NULL,
	"descricao" varchar(50),
	"idempresa" text NOT NULL,
	"codigo" bigint,
	"idbanco" bigint,
	"agencia" varchar(25),
	"abertura" date,
	"numeroconta" varchar(40),
	"gerente" varchar(40),
	"telefonegerente" varchar(20),
	"cnpjcpftitular" varchar(20),
	"observacao" varchar(150),
	"agenciadv" varchar(1),
	"contadv" varchar(2),
	"codigocedente" varchar(20),
	"codigocedentedv" varchar(1),
	"carteira" varchar(6),
	"operacao" varchar(5),
	"aceite" smallint DEFAULT 0,
	"nossonumeroseq" bigint,
	"codigofornecidoagencia" varchar(10),
	"codigofornecidoagenciadv" varchar(2),
	"instrucao1" varchar(100),
	"instrucao2" varchar(100),
	"instrucao3" varchar(100),
	"instrucao4" varchar(100),
	"especiedocumento" varchar(3),
	"tamanhocodigobarras" smallint DEFAULT 0,
	"tipoimpressao" smallint DEFAULT 0,
	"bancoemiteboleto" smallint,
	"arquivolicenca" varchar(255),
	"diasprotesto" smallint,
	"layoutarquivoremessa" varchar(100),
	"sequenciaremessa" integer,
	"outrodadoconfiguracao1" varchar(20),
	"outrodadoconfiguracao2" varchar(20),
	"layoutarquivoretorno" varchar(100),
	"layoutboleto" varchar(255),
	"caixa" smallint,
	"idfilial" bigint,
	"codigoinstrucao1" varchar(10),
	"codigoinstrucao2" varchar(10),
	"codigoinstrucao3" varchar(10),
	"currenttimemillis" bigint,
	"nometitular" varchar(20),
	"aceitecobrebem" varchar(5),
	"layoutboletopredefinido" varchar(255),
	"nomearquivoremessa" varchar(50),
	"formatoarquivo" smallint,
	"alturapapelboleto" smallint,
	"margemsuperiorboleto" smallint,
	"margemesquerdaboleto" smallint,
	"naogerarmensagemprotesto" smallint,
	"naogerarmensagemjuros" smallint,
	"naogerarmensagemmulta" smallint,
	"naogerarinstrucaocaixaremessa" smallint,
	"localpagamentoboleto" varchar(200),
	"dadoscedentecomprovantesacado" smallint,
	"naousarfatorvencimento" smallint,
	"valorinstrucao1" varchar(20),
	"valorinstrucao2" varchar(20),
	"valorinstrucao3" varchar(20),
	"processaretornonumerodocumento" smallint,
	"razaosocial" varchar(60),
	"cnpj" varchar(18),
	"cep" varchar(9),
	"idestado" bigint,
	"idcidade" bigint,
	"endereco" varchar(50),
	"numeroendereco" varchar(6),
	"bairro" varchar(50),
	"inativo" smallint,
	"bancogeranossonumero" smallint,
	"emissaoboleto" smallint,
	"distribuicaoboleto" smallint,
	"tipoprotesto" smallint,
	"tipojuros" smallint,
	"tipomulta" smallint,
	"naogerarregistrodetalhe3" smallint,
	"postobeneficiario" varchar(5),
	"tipoimpressaouboleto" smallint,
	"tipoidentificacaobeneficiario" smallint,
	"tipoidentificacaoentidade" smallint,
	"caminhoimagemboleto" varchar(255),
	"redimensionarimagemboleto" smallint,
	"localimpressaoinstrucaouboleto" smallint,
	"caixapadrao" smallint,
	"numerobeneficiarioboleto" varchar(30),
	"numeroversaolayoutarquivo" varchar(3),
	"numeroversaolayoutlote" varchar(3),
	"idconveniado" bigint,
	"idcontacontabilintegracao" bigint,
	"valoracrescimo" numeric(10, 2),
	"codificacaoarquivoremessa" varchar(10),
	"jurosencargos" numeric(12, 2),
	"multaencargos" numeric(12, 2),
	"imagemboleto" text,
	"tipovalidacaoarquivoretorno" smallint,
	"codigooperacao" varchar(20),
	"geracaonossonumero" smallint,
	"calcularencargosfinanceiros" smallint,
	"descontoantecipacao" numeric(5, 2),
	"desconsiderasabado" smallint,
	"desconsideradomingo" smallint,
	"diasdesconsiderarjuros" smallint,
	"diasdesconsiderarmulta" smallint,
	"diasdesconsiderardesconto" smallint,
	"receberpixpdv" smallint,
	"chavepix" varchar(100),
	"identidade" bigint,
	"tipointegracao" smallint,
	"chaveapi" varchar(512),
	"tipoambienteintegracao" smallint,
	"idcertificadointegracao" bigint,
	"diaslimitepagamento" smallint
);
--> statement-breakpoint
CREATE TABLE "contacorrentelancamento" (
	"id" text PRIMARY KEY NOT NULL,
	"idcontacorrente" text NOT NULL,
	"datahora" date,
	"tipo" char(1),
	"valor" numeric(12, 2),
	"saldoanterior" numeric(12, 2),
	"saldoatual" numeric(12, 2),
	"historico" text,
	"idusuario" text,
	"idplanocontas" bigint,
	"evento" bigint,
	"debito" numeric(12, 2),
	"documento" varchar(30),
	"currenttimemillis" bigint,
	"identificado" smallint,
	"depositonaoidentificado" smallint,
	"tiporateiocentrocusto" smallint,
	"idlancamentotransferencia" bigint,
	"dataconciliacao" date,
	"idusuarioconciliacao" text,
	"idlancamentoestornado" bigint
);
--> statement-breakpoint
CREATE TABLE "contas" (
	"id" text PRIMARY KEY NOT NULL,
	"idconta" text NOT NULL,
	"idprovedor" text NOT NULL,
	"idusuario" text NOT NULL,
	"accessToken" text,
	"refreshToken" text,
	"idToken" text,
	"accessTokenExpiresAt" timestamp(3),
	"refreshTokenExpiresAt" timestamp(3),
	"scope" text,
	"password" text,
	"createdAt" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp(3) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "empresas" (
	"id" text PRIMARY KEY NOT NULL,
	"nome" text NOT NULL,
	"cnpj" text NOT NULL,
	"telefone" text NOT NULL,
	"idproprietario" text NOT NULL,
	"criadoem" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"atualizadoem" timestamp(3) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "entidade" (
	"id" text PRIMARY KEY NOT NULL,
	"nome" varchar(60) NOT NULL,
	"razaosocial" varchar(60),
	"tipopessoa" smallint DEFAULT 0,
	"cnpjcpf" varchar(20) NOT NULL,
	"inscricaoestadual" varchar(20),
	"rg" varchar(20),
	"email" varchar(200),
	"telefone" varchar(40),
	"endereco" varchar(60),
	"numeroendereco" varchar(6),
	"complemento" varchar(50),
	"bairro" varchar(50),
	"idcidade" text,
	"idestado" text,
	"cep" varchar(6),
	"fax" varchar(40),
	"nascimento" date,
	"idplanocontas" text,
	"pais" text,
	"idempresa" text NOT NULL,
	"criadoem" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"atualizadoem" timestamp(3) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "financeiro" (
	"id" text PRIMARY KEY NOT NULL,
	"idempresa" text NOT NULL,
	"identidade" bigint,
	"tipo" char(1),
	"tipoorigem" smallint,
	"idorigem" bigint,
	"parcela" smallint,
	"documento" varchar(60),
	"idtipodocumentofinanceiro" bigint,
	"status" char(1),
	"emissao" date,
	"vencimento" date,
	"vencimentooriginal" date,
	"pagamento" date,
	"baixa" date,
	"valor" numeric(12, 2) DEFAULT '0.00',
	"saldo" numeric(12, 2) DEFAULT '0.00',
	"historico" text,
	"idbanco" bigint,
	"agencia" varchar(15),
	"numerocontacorrente" varchar(40),
	"cnpjcpfemitente" varchar(30),
	"emitente" varchar(60),
	"identidadedestino" bigint,
	"idcodigocontabil" bigint,
	"juros" double precision DEFAULT 0,
	"multa" double precision DEFAULT 0,
	"taxafinanciamento" double precision DEFAULT 0,
	"evento" bigint,
	"devolucaocodigo" smallint,
	"devolucaodescricao" varchar(50),
	"devolucaodata" date,
	"protestodate" date,
	"nossonumero" varchar(25),
	"idcontageraboleto" bigint,
	"numerocheque" varchar(10),
	"remessagerada" smallint,
	"boletoimpresso" smallint,
	"idtipocobranca" bigint,
	"idrepresentante" bigint,
	"percentualcomissaofaturamento" numeric(5, 2),
	"percentualcomissaoquitacao" numeric(12, 3),
	"currenttimemillis" bigint,
	"vencimentocalculoencargos" date,
	"valorbasecomissao" numeric(12, 3),
	"valorpagorecebido" numeric(12, 3),
	"codigobarras" varchar(100),
	"codigodigitado" varchar(100),
	"nomebandeira" varchar(50),
	"valororiginalcomissao" numeric(12, 3),
	"saldocomissao" numeric(12, 3),
	"entrada" date,
	"registro" timestamp(6),
	"baixa2" date,
	"idportador" bigint,
	"idcarteirageradauboleto" bigint,
	"tiporateiocentrocusto" smallint,
	"nomeadministradora" varchar(50),
	"iddependente" bigint,
	"dvnossonumero" varchar(3),
	"idadministradora" bigint,
	"idbandeira" bigint,
	"ultimaocorrenciabancaria" text,
	"idusuariosupervisor" text,
	"dataliberacaousuariosupervisor" timestamp(6),
	"acaoprocessamentoretorno" varchar(50),
	"instrucaocobrancaboleto" smallint,
	"diasinstrucaocobrancaboleto" smallint,
	"observacaoboleto" text,
	"idrepresentante2" bigint,
	"percentualcomissaoquitacao2" numeric(12, 3),
	"valororiginalcomissao2" numeric(12, 3),
	"saldocomissao2" numeric(12, 3),
	"statusjob" smallint,
	"extra1" varchar(512),
	"extra2" varchar(512),
	"extra3" varchar(512),
	"extra4" varchar(512),
	"extra5" varchar(512),
	"extra6" varchar(512),
	"datareferencia" date,
	"urlqrcode" text,
	"tipointegracao" smallint,
	"referenciaparceiro" varchar(256),
	"jsonretornodocumento" text,
	"totalparcelas" smallint,
	"urldocumento" text,
	"codigoecommerce" varchar(256),
	"codigopedidoecommerce" varchar(256),
	"idconfiguracaoecommerce" bigint,
	"idpagamentoapi" varchar(256),
	"autenticacaopagamentoapi" varchar(256),
	"statuscobrancaonline" smallint,
	"extra7" varchar(512),
	"extra8" varchar(512),
	"extra9" varchar(512),
	"extra10" varchar(512),
	"extra11" varchar(512),
	"extra12" varchar(512),
	"extra13" varchar(512),
	"extra14" varchar(512),
	"extra15" varchar(512),
	"extra16" varchar(512)
);
--> statement-breakpoint
CREATE TABLE "financeirolancamento" (
	"id" text PRIMARY KEY NOT NULL,
	"idfinanceiro" text NOT NULL,
	"valoranterior" numeric(12, 2),
	"desconto" numeric(12, 2),
	"valor" numeric(12, 2),
	"pagamento" date,
	"baixa" timestamp(6),
	"juros" numeric(12, 2),
	"multa" numeric(12, 2),
	"usuario" varchar(10),
	"cancelado" smallint DEFAULT (0),
	"datahoracancelado" timestamp(6),
	"evento" bigint NOT NULL,
	"historico" text,
	"reabertura" numeric(12, 2),
	"observacao" text,
	"currenttimemillis" bigint,
	"valorsubstituido" numeric(12, 2),
	"valordevolucao" numeric(12, 2),
	"datavencimentoanterior" date,
	"valorbaixa" numeric(12, 2),
	"acrescimo" numeric(12, 2),
	"baixa2" date,
	"idplanocontasjuros" smallint,
	"idplanocontasmulta" smallint,
	"idplanocontasdesconto" smallint,
	"idplanocontasacrescimo" smallint,
	"tiporateiocentrocustojuros" smallint,
	"tiporateiocentrocustomulta" smallint,
	"tiporateiocentrocustodesconto" smallint,
	"tiporateiocentrocustoacrescimo" smallint,
	"idportadoranterior" bigint,
	"idtipocobrancaanterior" bigint,
	"automatico" smallint
);
--> statement-breakpoint
CREATE TABLE "motivobaixafinanceiro" (
	"id" text PRIMARY KEY NOT NULL,
	"idempresa" text NOT NULL,
	"descricao" varchar(50) NOT NULL,
	"inativo" integer DEFAULT 0,
	"currenttimemillis" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "planocontas" (
	"id" text PRIMARY KEY NOT NULL,
	"idempresa" text NOT NULL,
	"codigo" varchar(30),
	"nome" varchar(40),
	"tipomovimento" varchar(1),
	"inativo" smallint,
	"classe" varchar(2),
	"currenttimemillis" bigint,
	"centrocustoobrigatorio" smallint,
	"tipoconta" integer,
	"idcontacontabilintegracao" bigint,
	"exportaparacontabilidade" smallint,
	"idgrupodre" bigint,
	"idplanocontas" text
);
--> statement-breakpoint
CREATE TABLE "_prisma_migrations" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"checksum" varchar(64) NOT NULL,
	"finished_at" timestamp with time zone,
	"migration_name" varchar(255) NOT NULL,
	"logs" text,
	"rolled_back_at" timestamp with time zone,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"applied_steps_count" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sessoes" (
	"id" text PRIMARY KEY NOT NULL,
	"expiresAt" timestamp(3) NOT NULL,
	"token" text NOT NULL,
	"createdAt" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp(3) NOT NULL,
	"ipAddress" text,
	"userAgent" text,
	"idusuario" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tipodocumentofinanceiro" (
	"id" text PRIMARY KEY NOT NULL,
	"descricao" varchar(50) NOT NULL,
	"acao" integer NOT NULL,
	"saidafechamento" integer DEFAULT 0,
	"inativo" integer DEFAULT 0,
	"integracaixabanco" integer DEFAULT 0,
	"baixageracodigobanco" integer DEFAULT 0,
	"currenttimemillis" bigint NOT NULL,
	"permitegerarboleto" integer,
	"idmotivobaixafinanceiro" text,
	"utilizadoemnegociao" integer,
	"enviamobile" integer,
	"tipousuario" integer DEFAULT 0,
	"localusoboleto" integer DEFAULT 0,
	"resgatarboleto" integer DEFAULT 0,
	"calcularencargofinanceiro" integer,
	"juros" integer DEFAULT 0,
	"multa" integer DEFAULT 0,
	"descontoantecipacao" integer DEFAULT 0,
	"desconsiderasabado" integer DEFAULT 0,
	"desconsideradependente" integer DEFAULT 0,
	"diasdeconsiderarjuros" integer DEFAULT 0,
	"diasdeconsiderarmulta" integer DEFAULT 0,
	"diasdesconsiderardesconto" integer DEFAULT 0,
	"tipocalculojuros" integer,
	"consideraparainadimplencia" integer DEFAULT 0,
	"enviaecommerce" integer,
	"formapagamentonfe" varchar,
	"tipocobrancasaas" integer,
	"codigomercos" integer,
	"idempresa" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "usuario_empresas" (
	"id" text PRIMARY KEY NOT NULL,
	"idusuario" text NOT NULL,
	"idempresa" text NOT NULL,
	"criadoem" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"atualizadoem" timestamp(3) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "usuarios" (
	"id" text PRIMARY KEY NOT NULL,
	"nome" text NOT NULL,
	"email" text NOT NULL,
	"emailverificado" boolean NOT NULL,
	"perfil" text DEFAULT 'usuario' NOT NULL,
	"criadoem" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"atualizadoem" timestamp(3) NOT NULL,
	"imagem" text,
	"maxempresas" integer,
	CONSTRAINT "usuarios_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "verificacoes" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expiresAt" timestamp(3) NOT NULL,
	"createdAt" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_idusuario_fkey" FOREIGN KEY ("idusuario") REFERENCES "public"."usuarios"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "contas" ADD CONSTRAINT "contas_idusuario_fkey" FOREIGN KEY ("idusuario") REFERENCES "public"."usuarios"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "empresas" ADD CONSTRAINT "empresas_idproprietario_fkey" FOREIGN KEY ("idproprietario") REFERENCES "public"."usuarios"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "entidade" ADD CONSTRAINT "entidades_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "planocontas" ADD CONSTRAINT "planocontas_idplanocontas_fkey" FOREIGN KEY ("idplanocontas") REFERENCES "public"."planocontas"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "sessoes" ADD CONSTRAINT "sessoes_idusuario_fkey" FOREIGN KEY ("idusuario") REFERENCES "public"."usuarios"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "usuario_empresas" ADD CONSTRAINT "usuario_empresas_idusuario_fkey" FOREIGN KEY ("idusuario") REFERENCES "public"."usuarios"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "usuario_empresas" ADD CONSTRAINT "usuario_empresas_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
CREATE INDEX "idx_contacorrentelanc_evento" ON "contacorrentelancamento" USING btree ("evento" int8_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "empresas_cnpj_key" ON "empresas" USING btree ("cnpj" text_ops);--> statement-breakpoint
CREATE INDEX "entidades_idempresa_idx" ON "entidade" USING btree ("idempresa" text_ops);--> statement-breakpoint
CREATE INDEX "entidades_email_idx" ON "entidade" USING btree ("email" text_ops);--> statement-breakpoint
CREATE INDEX "idx_fin_entid_tipo_status" ON "financeiro" USING btree ("identidade" int8_ops,"tipo" bpchar_ops,"status" bpchar_ops);--> statement-breakpoint
CREATE INDEX "idx_financeiro_emissao" ON "financeiro" USING btree ("emissao" date_ops);--> statement-breakpoint
CREATE INDEX "idx_financeiro_idfilial" ON "financeiro" USING btree ("idempresa" text_ops);--> statement-breakpoint
CREATE INDEX "idx_financeiro_sped" ON "financeiro" USING btree ("idorigem" int8_ops,"tipoorigem" int2_ops);--> statement-breakpoint
CREATE INDEX "idx_financeiro_status" ON "financeiro" USING btree ("status" bpchar_ops);--> statement-breakpoint
CREATE INDEX "idx_financeiro_tipo" ON "financeiro" USING btree ("tipo" bpchar_ops);--> statement-breakpoint
CREATE INDEX "idx_financeiro_vencimento" ON "financeiro" USING btree ("vencimento" date_ops);--> statement-breakpoint
CREATE INDEX "idx_finlan_evento" ON "financeirolancamento" USING btree ("evento" int8_ops);--> statement-breakpoint
CREATE INDEX "idx_finlan_idfinanceiro" ON "financeirolancamento" USING btree ("idfinanceiro" text_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "sessoes_token_key" ON "sessoes" USING btree ("token" text_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "usuarios_email_key" ON "usuarios" USING btree ("email" text_ops);