CREATE TABLE "area" (
	"id" text PRIMARY KEY NOT NULL,
	"idempresa" text NOT NULL,
	"inativo" smallint,
	"descricao" varchar(50),
	"datacadastro" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"dataultimaalteracao" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"idultimousuarioalteracao" text NOT NULL,
	"idusuariocadastro" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cest" (
	"id" text PRIMARY KEY NOT NULL,
	"idempresa" text NOT NULL,
	"inativo" integer DEFAULT 0,
	"descricao" text NOT NULL,
	"descricaoncm" text NOT NULL,
	"codigo" varchar(10) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cfop" (
	"id" text PRIMARY KEY NOT NULL,
	"idempresa" text NOT NULL,
	"abatericmsbasepiscofins" smallint,
	"abatericmsdesonbasepiscofins" smallint,
	"abatericmsst30" smallint,
	"adicionarpiscofinsinfcomp" smallint,
	"aliquotacofins" numeric(12, 4),
	"aliquotacofinsentrada" numeric(12, 4),
	"aliquotacofinsretido" numeric(5, 2),
	"aliquotaipientrada" numeric(12, 4),
	"aliquotaipisaida" numeric(12, 4),
	"aliquotapis" numeric(12, 4),
	"aliquotapisentrada" numeric(12, 4),
	"aliquotapisretido" numeric(5, 2),
	"calculabaseicmsparaelemesmo" smallint,
	"calculafundocombatepobreza" smallint,
	"calculardifalcomaliquotazero" smallint,
	"calculardiferencialaliqicmsst" smallint,
	"calcularicmsefetivo" varchar(1),
	"calcularicmsstpelocusto" smallint,
	"calcularimpostoaproximado" smallint,
	"cfopentradasped" varchar(3),
	"cfopsaidasped" varchar(3),
	"codigo" varchar(20),
	"codigoantecipacao" integer,
	"codigocfopservicog2ka" varchar(1),
	"conferencianotafiscal" smallint,
	"conferenciapedido" smallint,
	"configuracaoadicionalnfse1" varchar(10),
	"configuracaoadicionalnfse2" varchar(10),
	"configuracaoadicionalnfse3" varchar(10),
	"consideracustomedio" smallint,
	"consideradespaduanbaseicms" smallint,
	"consideradevolucaovenda" smallint,
	"considerafretebaseipi" smallint,
	"consideraicmsstbasepiscofins" smallint,
	"consideraimpimportacaobaseicms" smallint,
	"considerainscricaoestadualsub" smallint,
	"consideraiofbaseicms" smallint,
	"consideraipi" smallint,
	"consideraipibaseicms" smallint,
	"consideraipibaseicmsst" smallint,
	"consideraipibasepiscofins" smallint,
	"consideraoutdespbaseipi" smallint,
	"considerarcofinsbaseicms" smallint,
	"considerardespimpbasepiscof" smallint,
	"considerarpisbaseicms" smallint,
	"considerarproduto" smallint,
	"considerarservico" smallint,
	"consideravenda" smallint,
	"consignacao" smallint,
	"consignacaoentrada" smallint,
	"consumidorfinal" smallint,
	"contranotafunrural" smallint,
	"contribuinte" integer,
	"controlasaldofiscal" smallint,
	"cstac" varchar(3),
	"cstal" varchar(3),
	"cstam" varchar(3),
	"cstap" varchar(3),
	"cstba" varchar(3),
	"cstce" varchar(3),
	"cstcofins" varchar(2),
	"cstcofinsentrada" varchar(2),
	"cstdf" varchar(3),
	"cstes" varchar(3),
	"cstex" varchar(3),
	"cstgo" varchar(3),
	"cstipientrada" varchar(3),
	"cstipisaida" varchar(3),
	"cstma" varchar(3),
	"cstmg" varchar(3),
	"cstms" varchar(3),
	"cstmt" varchar(3),
	"cstpa" varchar(3),
	"cstpb" varchar(3),
	"cstpe" varchar(3),
	"cstpi" varchar(3),
	"cstpis" varchar(2),
	"cstpisentrada" varchar(2),
	"cstpr" varchar(3),
	"cstrj" varchar(3),
	"cstrn" varchar(3),
	"cstro" varchar(3),
	"cstrr" varchar(3),
	"cstrs" varchar(3),
	"cstsc" varchar(3),
	"cstse" varchar(3),
	"cstservico" varchar(3),
	"cstsp" varchar(3),
	"cstto" varchar(3),
	"currenttimemillis" bigint,
	"descricao" varchar(1024),
	"descricaocompleta" varchar(320),
	"destaqueimposto" smallint,
	"digitarimpostositemnotasaida" smallint,
	"digitartotalitemmanualmente" smallint,
	"enviartagicmsstretzero" smallint,
	"enviartagsdiferimentototal" smallint,
	"exigirdocumentoreferenciado" smallint,
	"finalidadeemissaonfe" smallint,
	"forcaricmssn" smallint,
	"forcaripidevolvido" smallint,
	"fundamentacaolegalestado" varchar(100),
	"gerarcreditoicmsst" smallint,
	"gerarcreditoipi" smallint,
	"habilitabaseipiitemnota" smallint,
	"habilitabasepiscofinsitemnota" smallint,
	"icmsac" numeric(5, 2),
	"icmsal" numeric(5, 2),
	"icmsam" numeric(5, 2),
	"icmsap" numeric(5, 2),
	"icmsba" numeric(5, 2),
	"icmsce" numeric(5, 2),
	"icmsdevidouforigemconhecimento" smallint,
	"icmsdf" numeric(5, 2),
	"icmses" numeric(5, 2),
	"icmsex" numeric(5, 2),
	"icmsgo" numeric(5, 2),
	"icmsma" numeric(5, 2),
	"icmsmg" numeric(5, 2),
	"icmsms" numeric(5, 2),
	"icmsmt" numeric(5, 2),
	"icmspa" numeric(5, 2),
	"icmspb" numeric(5, 2),
	"icmspe" numeric(5, 2),
	"icmspi" numeric(5, 2),
	"icmspr" numeric(5, 2),
	"icmsrj" numeric(5, 2),
	"icmsrn" numeric(5, 2),
	"icmsro" numeric(5, 2),
	"icmsrr" numeric(5, 2),
	"icmsrs" numeric(5, 2),
	"icmssc" numeric(5, 2),
	"icmsse" numeric(5, 2),
	"icmssp" numeric(5, 2),
	"icmsstac" numeric(5, 2),
	"icmsstal" numeric(5, 2),
	"icmsstam" numeric(5, 2),
	"icmsstap" numeric(5, 2),
	"icmsstba" numeric(5, 2),
	"icmsstce" numeric(5, 2),
	"icmsstdf" numeric(5, 2),
	"icmsstes" numeric(5, 2),
	"icmsstex" numeric(5, 2),
	"icmsstgo" numeric(5, 2),
	"icmsstma" numeric(5, 2),
	"icmsstmg" numeric(5, 2),
	"icmsstms" numeric(5, 2),
	"icmsstmt" numeric(5, 2),
	"icmsstpa" numeric(5, 2),
	"icmsstpb" numeric(5, 2),
	"icmsstpe" numeric(5, 2),
	"icmsstpi" numeric(5, 2),
	"icmsstpr" numeric(5, 2),
	"icmsstrj" numeric(5, 2),
	"icmsstrn" numeric(5, 2),
	"icmsstro" numeric(5, 2),
	"icmsstrr" numeric(5, 2),
	"icmsstrs" numeric(5, 2),
	"icmsstsc" numeric(5, 2),
	"icmsstse" numeric(5, 2),
	"icmsstsp" numeric(5, 2),
	"icmsstto" numeric(5, 2),
	"icmsto" numeric(5, 2),
	"idajusteapuracaoicmsdevoluc" text,
	"idajusteapuracaoipidevoluc" text,
	"idajustedocfiscalcreditoicms" text,
	"idbasecalculocredito" text,
	"idcondicaopagamento" text,
	"idcontribuicaosocialapurada" text,
	"idcontribuicaosocialapurcofins" text,
	"idenquadramentoipientrada" text,
	"idenquadramentoipisaida" text,
	"identidadeoperacaofiscal" text,
	"idestadodestino" text,
	"idestadoorigem" text,
	"idfilial" text,
	"idincentivofiscalorigem" text,
	"idnaturezadevolucao" text,
	"idnaturezanaocontribuinte" text,
	"idnaturezaoperacaoinversa" text,
	"idnbs" text,
	"idobslancfiscalcreditoicms" text,
	"idoperacaofiscal" text,
	"idplanocontas" text,
	"idreceitasemcontribuicao" text,
	"idtipocredito" text,
	"idtipodocumentofinanceiro" text,
	"idtipoentidadeopfiscal" text,
	"importacao" smallint,
	"inativa" smallint,
	"informartotaismanualmente" smallint,
	"integracao" smallint,
	"interestadualdestmesmauf" smallint,
	"iss" numeric(7, 4),
	"modocalculoipientrada" smallint,
	"modocalculoipisaida" smallint,
	"movimentoregistroc170" smallint,
	"multiplicadorbaseicms" numeric(12, 6),
	"naoabaterfcpinternofcpst" smallint,
	"naoaplicarmva" smallint,
	"naobaixarestoque" smallint,
	"naoconsiddescontobaseicms" smallint,
	"naoconsiddescontobaseicmsst" smallint,
	"naoconsiddescontobasepiscofins" smallint,
	"naoconsiddescontocontsocial" smallint,
	"naoconsiddescontoimpostorenda" smallint,
	"naoconsiddescontoinss" smallint,
	"naoconsiddescontoiss" smallint,
	"naoconsiddescpiscofinsretido" smallint,
	"naoconsiderafretebaseicms" smallint,
	"naoconsiderafretebaseicmsst" smallint,
	"naoconsideraoutdespbaseicms" smallint,
	"naoconsiderapiscofinsproduto" smallint,
	"naoconsiderarvlnotafiscalitem" varchar(3),
	"naoconsideratribespecproduto" smallint,
	"naoconsidfretebasepiscofins" smallint,
	"naoconsidoutdespbasepiscofins" smallint,
	"naoconsidoutrasdespbaseicmsst" smallint,
	"naoconsidsegbasepiscofins" smallint,
	"naogeracreditopiscofins" smallint,
	"naomostrarreducaoicmsst" smallint,
	"naosomarfretenototal" smallint,
	"notacomplementar" smallint,
	"observacaoitemnotafiscal" text,
	"observacaonotafiscal" text,
	"observacaonotafiscalfisco" text,
	"operacaocomcreditodeestimulo" smallint,
	"ordemoperacaofiscal" smallint,
	"percaproveitamentoicmslc123" numeric(7, 4),
	"perccontribuicaosocial" numeric(5, 2),
	"percentualfunrural" numeric(5, 2),
	"percentualpartilhadifal" numeric(5, 2),
	"percimpostorenda" numeric(5, 2),
	"percinss" numeric(5, 2),
	"percreducaoinss" numeric(5, 2),
	"permitecreditopiscofinspf" smallint,
	"permitenfnormalsomentealiqicms" smallint,
	"permitenotasemvalor" smallint,
	"permitirbaixarlotevencido" smallint,
	"permitircfopinternaopexterior" smallint,
	"posseitem" varchar(1),
	"possuiincentivosfiscais" smallint,
	"possuirepasseicmsst" smallint,
	"presencaconsumidor" smallint,
	"reducaoicmsac" numeric(9, 6),
	"reducaoicmsal" numeric(9, 6),
	"reducaoicmsam" numeric(9, 6),
	"reducaoicmsap" numeric(9, 6),
	"reducaoicmsba" numeric(9, 6),
	"reducaoicmsce" numeric(9, 6),
	"reducaoicmsdf" numeric(9, 6),
	"reducaoicmses" numeric(9, 6),
	"reducaoicmsex" numeric(9, 6),
	"reducaoicmsgo" numeric(9, 6),
	"reducaoicmsma" numeric(9, 6),
	"reducaoicmsmg" numeric(9, 6),
	"reducaoicmsms" numeric(9, 6),
	"reducaoicmsmt" numeric(9, 6),
	"reducaoicmspa" numeric(9, 6),
	"reducaoicmspb" numeric(9, 6),
	"reducaoicmspe" numeric(9, 6),
	"reducaoicmspi" numeric(9, 6),
	"reducaoicmspr" numeric(9, 6),
	"reducaoicmsrj" numeric(9, 6),
	"reducaoicmsrn" numeric(9, 6),
	"reducaoicmsro" numeric(9, 6),
	"reducaoicmsrr" numeric(9, 6),
	"reducaoicmsrs" numeric(9, 6),
	"reducaoicmssc" numeric(9, 6),
	"reducaoicmsse" numeric(9, 6),
	"reducaoicmssp" numeric(9, 6),
	"reducaoicmsstac" numeric(9, 6),
	"reducaoicmsstal" numeric(9, 6),
	"reducaoicmsstam" numeric(9, 6),
	"reducaoicmsstap" numeric(9, 6),
	"reducaoicmsstba" numeric(9, 6),
	"reducaoicmsstce" numeric(9, 6),
	"reducaoicmsstdf" numeric(9, 6),
	"reducaoicmsstes" numeric(9, 6),
	"reducaoicmsstex" numeric(9, 6),
	"reducaoicmsstgo" numeric(9, 6),
	"reducaoicmsstma" numeric(9, 6),
	"reducaoicmsstmg" numeric(9, 6),
	"reducaoicmsstms" numeric(9, 6),
	"reducaoicmsstmt" numeric(9, 6),
	"reducaoicmsstpa" numeric(9, 6),
	"reducaoicmsstpb" numeric(9, 6),
	"reducaoicmsstpe" numeric(9, 6),
	"reducaoicmsstpi" numeric(9, 6),
	"reducaoicmsstpr" numeric(9, 6),
	"reducaoicmsstrj" numeric(9, 6),
	"reducaoicmsstrn" numeric(9, 6),
	"reducaoicmsstro" numeric(9, 6),
	"reducaoicmsstrr" numeric(9, 6),
	"reducaoicmsstrs" numeric(9, 6),
	"reducaoicmsstsc" numeric(9, 6),
	"reducaoicmsstse" numeric(9, 6),
	"reducaoicmsstsp" numeric(9, 6),
	"reducaoicmsstto" numeric(9, 6),
	"reducaoicmsto" numeric(9, 6),
	"reducaoiss" numeric(7, 4),
	"regimeespecial" smallint,
	"registrarproducaovenda" smallint,
	"retencaoiss" numeric(7, 4),
	"retercontribuicaosocial" smallint,
	"reterimpostorenda" smallint,
	"reterinss" smallint,
	"reterpiscofins" smallint,
	"semrepercussaofiscalpe" smallint,
	"situacaotributaria" varchar(3),
	"situacaotributariasn" varchar(3),
	"somarafrmmtotal" smallint,
	"somarcofinsoutrasdesp" smallint,
	"somarcofinstotal" smallint,
	"somardespacesoutrasdesp" smallint,
	"somardespesasaduaneirastotal" smallint,
	"somaricmsoutrasdesp" smallint,
	"somaricmstotal" smallint,
	"somariitotalproduto" smallint,
	"somarpisoutrasdesp" smallint,
	"somarpistotal" smallint,
	"somarsiscomexoutrasdesp" smallint,
	"somarsiscomextotal" smallint,
	"tipocalculoicmsretant" smallint,
	"tipoenquadramento" smallint,
	"tipoenquadramentoorigem" smallint,
	"tipoproduto" varchar(2),
	"tiporemessaemterceiros" smallint,
	"tipovalorpreco" smallint,
	"tributacaoespecial" varchar(6),
	"tributacaoservico" varchar(7),
	"tributamunicipioprestador" smallint,
	"utilizartodasoperacoes" smallint,
	"valorminimoretencao" numeric(12, 2),
	"zerarfcpterceiros" smallint
);
--> statement-breakpoint
CREATE TABLE "cfoppadrao" (
	"id" text PRIMARY KEY NOT NULL,
	"idempresa" text NOT NULL,
	"finalidade" varchar(1024) NOT NULL,
	"inativo" integer DEFAULT 0,
	"nome" varchar(1024) NOT NULL,
	"codigo" varchar(20) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "condicaopagamento" (
	"id" text PRIMARY KEY NOT NULL,
	"idempresa" text NOT NULL,
	"codigo" varchar(10),
	"currenttimemillis" bigint,
	"descricao" varchar(512),
	"dialimite" smallint,
	"diavencimento" smallint,
	"dodispositivo" smallint,
	"enviamobile" smallint,
	"escopo" smallint,
	"fator" numeric(5, 4),
	"inativo" smallint,
	"mesescarencia" smallint,
	"naoutilizarnopdv" smallint,
	"parcelas" smallint,
	"percentual" numeric(5, 2),
	"podeserflex" smallint,
	"prazomanipulacao" smallint,
	"prazomedio" smallint,
	"prazos" varchar(512),
	"tipo" smallint
);
--> statement-breakpoint
CREATE TABLE "dav" (
	"id" text PRIMARY KEY NOT NULL,
	"idempresa" text NOT NULL,
	"acrescimo" numeric(12, 2),
	"agenciabancocheque" varchar(10),
	"anofabricacao" smallint,
	"aprazo" numeric(12, 2),
	"aprovado" smallint,
	"assinatura" text,
	"avista" numeric(12, 2),
	"bairroentrega" varchar(50),
	"baseicms" numeric(12, 2),
	"baseicmssubstituicao" numeric(12, 2),
	"carteiradigital" numeric(12, 2),
	"ccf" integer,
	"celularentrega" varchar(40),
	"cepentrega" varchar(9),
	"cheque" numeric(12, 2),
	"cnpjcpfcliente" varchar(18),
	"cnpjcpfentrega" varchar(20),
	"cnpjcpftransportadora" varchar(18),
	"cnpjfilial" varchar(18),
	"codigo" bigint,
	"codigoecommerce" varchar(50),
	"codigomobile" varchar(36),
	"codigoorigemecommerce" varchar(50),
	"codigorastreio" varchar(200),
	"codigotabelafinanciamento" varchar(10),
	"cofins" numeric(12, 2),
	"comissaorepresentante" numeric(12, 2),
	"complementoentrega" varchar(60),
	"conferido" smallint,
	"coo" integer,
	"cooger" integer,
	"cpfcnpjemitentecheque" varchar(20),
	"cupomemitido" smallint,
	"currenttimemillis" bigint,
	"data" date,
	"dataalteracao" timestamp(3),
	"datacancelamento" date,
	"datahoradespacho" timestamp(3),
	"datahorafaturamento" timestamp(3),
	"datahoraimpressao" timestamp(3),
	"datahorarecebimento" timestamp(3),
	"dataimportacao" date,
	"datainclusao" timestamp(3),
	"datapedidomobile" timestamp(3),
	"dataprimeirovencimento" date,
	"deposito" numeric(12, 2),
	"desconto" numeric(12, 2),
	"descontosubtotal" numeric(12, 2),
	"despachomelhorenvio" smallint,
	"devolucao" numeric(12, 2),
	"diferencafianciamento" numeric(12, 2),
	"dinheiro" numeric(12, 2),
	"ecfmarca" varchar(20),
	"ecfmfadicional" varchar(1),
	"ecfmodelo" varchar(20),
	"ecfserie" varchar(20),
	"ecftipo" varchar(7),
	"emailentrega" varchar(60),
	"enderecoentrega" varchar(60),
	"enderecotransportadora" varchar(50),
	"entrega" timestamp(3),
	"especietransportadora" varchar(60),
	"extra1" varchar(512),
	"extra2" varchar(512),
	"extra3" varchar(512),
	"extra4" varchar(512),
	"extra5" varchar(512),
	"extra6" varchar(512),
	"extra7" varchar(512),
	"extra8" varchar(512),
	"extra9" varchar(512),
	"extra10" varchar(512),
	"hash" bigint,
	"hashpafnfce" bigint,
	"icms" numeric(12, 2),
	"icmsfundopobrezainterno" numeric(12, 2),
	"icmsfundopobrezast" numeric(12, 2),
	"icmssubstituicao" numeric(12, 2),
	"idadiantamento" text,
	"idadmcarteiradigital" text,
	"idbancocheque" text,
	"idcarrinhocompras" text,
	"idcfop" text,
	"idcidadeentrega" text,
	"idcidadetransportadora" text,
	"idcliente" text,
	"idcondicaopagamento" text,
	"idconfiguracaoecommerce" text,
	"idcontacorrentedeposito" text,
	"idcontacorrentepix" text,
	"idcupomshop" text,
	"iddavgerada" text,
	"iddavmesclada" text,
	"iddavoriginal" text,
	"identidaderemessaecommerce" text,
	"identificacao" varchar(20),
	"identregamercadolivre" text,
	"idestadoentrega" text,
	"idestadotransportadora" text,
	"idestadoveiculotransportadora" text,
	"idfilial" text,
	"idfinalizador" text,
	"idformaentregaregiao" text,
	"idlocalestoque" text,
	"idlocalretirada" text,
	"idlocalretiradanf" text,
	"idnfce" text,
	"idnotafiscal" text,
	"idnotaressaecomerce" text,
	"idnotavendaecomerce" text,
	"idoperacao" text,
	"idoperacaofiscal" text,
	"idrastreioecommerce" text,
	"idrepresentante" text,
	"idrepresentante2" text,
	"idroteirovendedor" text,
	"idtabelafinanciamento" text,
	"idtabelafinanciamentoparcela" text,
	"idtabelafinanparcelacond" text,
	"idtabelapreco" text,
	"idtipodocumentofinanceiro" text,
	"idtipopedido" text,
	"idtransacaofinanceira" text,
	"idtransportadora" text,
	"idtranspremessaecommerce" text,
	"idusuario" text,
	"idusuariocancelamento" text,
	"idusuarioconferencia" text,
	"idusuariodescontofin" text,
	"idusuariofaturamento" text,
	"idusuarioliberouatraso" text,
	"idusuarioliberoulimite" text,
	"ietransportadora" varchar(20),
	"impresso" smallint,
	"incluidoporcliente" smallint,
	"inscricaoestadual" varchar(20),
	"ipi" numeric(12, 2),
	"latitudeentrega" numeric(10, 7),
	"longitudeentrega" numeric(10, 7),
	"marca" varchar(30),
	"marcatransportadora" varchar(60),
	"modelo" varchar(30),
	"nomecliente" varchar(60),
	"nomeemitentecheque" varchar(60),
	"nomerazaosocialentrega" varchar(50),
	"numerocheque" varchar(20),
	"numerocontacorrentebancocheque" varchar(10),
	"numeroenderecoentrega" varchar(6),
	"numeroenderecotransportadora" varchar(6),
	"numeroparcelas" smallint,
	"numeroserie" varchar(30),
	"numerotransportadora" varchar(60),
	"objnotaecommerce" text,
	"observacao" text,
	"outros" numeric(12, 2),
	"pautapreco" smallint,
	"pdv" smallint,
	"pedidocliente" varchar(50),
	"pedidoclientexped" varchar(60),
	"pedidoreferenteadiantamento" smallint,
	"percentualdescontosubtotal" numeric(5, 2),
	"pesobrutotransportadora" numeric(12, 3),
	"pesoliquidotransportadora" numeric(12, 3),
	"pis" numeric(12, 2),
	"pix" numeric(12, 2),
	"placa" varchar(10),
	"placaveiculotransportadora" varchar(8),
	"plano" varchar(255),
	"posaprazo" numeric(12, 2),
	"posavista" numeric(12, 2),
	"quantidadetransportadora" numeric(15, 6),
	"renavam" varchar(11),
	"status" smallint,
	"statusecommerce" varchar(50),
	"taxa" numeric(12, 2),
	"telefoneentrega" varchar(40),
	"temfinanciamento" smallint,
	"tipocompra" smallint,
	"tipodocumento" smallint,
	"tipofrete" smallint,
	"tipoparcela" smallint,
	"tipopedidoecommerce" varchar(50),
	"tipopessoa" smallint,
	"tipopessoaentrega" smallint,
	"tipovenda" smallint,
	"titulodav" varchar(30),
	"trocoshop" numeric(12, 2),
	"urlrastreio" varchar(200),
	"validade" date,
	"valor" numeric(12, 2),
	"valoracrescimo" numeric(12, 2),
	"valordesconto" numeric(12, 2),
	"valordescontousuario" numeric(12, 2),
	"valorentrada" numeric(12, 2),
	"valorentradaoriginal" numeric(12, 2),
	"valorfrete" numeric(12, 2),
	"valorprestacao" numeric(12, 2),
	"valorprestacaooriginal" numeric(12, 2),
	"valortotalfinanceiro" numeric(12, 2),
	"valortotalparcelas" numeric(12, 2),
	"valortotalparcelasoriginal" numeric(12, 2),
	"vencimentocheque" date
);
--> statement-breakpoint
CREATE TABLE "departamento" (
	"id" text PRIMARY KEY NOT NULL,
	"idempresa" text NOT NULL,
	"codigo" varchar(20) NOT NULL,
	"descricao" varchar(12) NOT NULL,
	"datacadastro" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"dataultimaalteracao" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"idultimousuarioalteracao" text NOT NULL,
	"idusuariocadastro" text NOT NULL,
	"inativo" integer DEFAULT 0
);
--> statement-breakpoint
CREATE TABLE "enquatramentoipi" (
	"id" text PRIMARY KEY NOT NULL,
	"idempresa" text NOT NULL,
	"codigo" varchar(20) NOT NULL,
	"descricao" varchar(100) NOT NULL,
	"grupocst" varchar(20) NOT NULL,
	"datacadastro" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"dataultimaalteracao" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hierarquia" (
	"id" text PRIMARY KEY NOT NULL,
	"idempresa" text NOT NULL,
	"aliquotacofins" numeric(12, 4),
	"aliquotacofinsentrada" numeric(12, 4),
	"aliquotafcp" numeric(5, 2),
	"aliquotafcpnf" numeric(5, 2),
	"aliquotaicmsinterna" numeric(5, 2),
	"aliquotaicmsnf" numeric(5, 2),
	"aliquotapis" numeric(12, 4),
	"aliquotapisentrada" numeric(12, 4),
	"aliquotareducaoicmsnfcesat" numeric(7, 4),
	"classe" smallint,
	"codigo" varchar(30),
	"comissao" numeric(5, 2),
	"comissaoaprazo" numeric(5, 2),
	"comissaoaprazopauta1" numeric(5, 2),
	"comissaoaprazopauta2" numeric(5, 2),
	"comissaoaprazopauta3" numeric(5, 2),
	"comissaoaprazopauta4" numeric(5, 2),
	"comissaoavista" numeric(5, 2),
	"comissaoavistapauta1" numeric(5, 2),
	"comissaoavistapauta2" numeric(5, 2),
	"comissaoavistapauta3" numeric(5, 2),
	"comissaoavistapauta4" numeric(5, 2),
	"comissaogestaopreco" numeric(5, 2),
	"comissaopauta1" numeric(5, 2),
	"comissaopauta2" numeric(5, 2),
	"comissaopauta3" numeric(5, 2),
	"comissaopauta4" numeric(5, 2),
	"comissaoquitacao" numeric(5, 2),
	"comissaoquitacaopauta1" numeric(5, 2),
	"comissaoquitacaopauta2" numeric(5, 2),
	"comissaoquitacaopauta3" numeric(5, 2),
	"comissaoquitacaopauta4" numeric(5, 2),
	"cstcofins" varchar(2),
	"cstcofinsentrada" varchar(2),
	"csticms" varchar(3),
	"cstpis" varchar(2),
	"cstpisentrada" varchar(2),
	"cstsnicms" varchar(3),
	"currenttimemillis" bigint,
	"custovariavelgestaopreco" numeric(5, 2),
	"diferencialicmsgestaocusto" numeric(5, 2),
	"enviamobile" smallint,
	"iat" char(1),
	"icone" text,
	"idbasecalculocredito" text,
	"idbeneficiofiscalnf" text,
	"idbeneficiofiscaloperacao" text,
	"idcest" text,
	"idcomprador" text,
	"idcontribuicaoprevidenciaria" text,
	"idcontribuicaosocialapurada" text,
	"idcontribuicaosocialapurcofins" text,
	"identificacliente" smallint,
	"identificaconsumidor" smallint,
	"idncm" text,
	"idreceitasemcontribuicao" text,
	"idtabelafinanciamento" text,
	"idtabelamva" text,
	"idtipocredito" text,
	"ipi" numeric(5, 2),
	"ipientrada" numeric(5, 2),
	"ippt" char(1),
	"lucrobrutomaximo" numeric(12, 2),
	"lucrobrutominimo" numeric(12, 2),
	"modalidadeicmsst" smallint,
	"modocalculoipi" smallint,
	"modocalculoipientrada" smallint,
	"motivodesoneracaoicms" smallint,
	"motivodesoneracaonf" smallint,
	"ncm" varchar(10),
	"nome" varchar(40),
	"nummaxcombinacoes" integer,
	"origem" smallint,
	"outrasdespesasgestaopreco" numeric(5, 2),
	"outrosimpostosgestaopreco" numeric(5, 2),
	"outrosvalorescredgestaocusto" numeric(5, 2),
	"outrosvaloresdebgestaocusto" numeric(5, 2),
	"pedevendedor" smallint,
	"percentualcustoindireto" numeric(5, 2),
	"percentualmarkdownmaximo" numeric(12, 2),
	"percentualmarkdownminimo" numeric(12, 2),
	"percentualmarkupmaximo" numeric(12, 2),
	"percentualmarkupminimo" numeric(12, 2),
	"percentualreducaoicms" numeric(7, 4),
	"percentualreducaomva" numeric(5, 2),
	"possuialiquotacombatepobreza" smallint,
	"precodiferenciado" smallint,
	"prefixogrupoproduto" varchar(10),
	"produtoseramodelofichatecnica" smallint,
	"produtoteracotacao" smallint,
	"situacaotributariaentrada" varchar(3),
	"situacaotributariaipi" varchar(3),
	"situacaotributariaipientrada" varchar(3),
	"situacaotributariasnentrada" varchar(3),
	"tabelafinanciamento" varchar(6),
	"tipoproduto" varchar(2),
	"tributacao" varchar(7),
	"tributacaoespecial" varchar(7),
	"tributacaoespecialnfcesat" varchar(3),
	"tributacaosn" varchar(3),
	"valoricmsst" numeric(12, 2)
);
--> statement-breakpoint
CREATE TABLE "localretirada" (
	"id" text PRIMARY KEY NOT NULL,
	"idempresa" text NOT NULL,
	"bairro" varchar(60),
	"cep" varchar(9),
	"cnpjcpf" varchar(20),
	"complemento" varchar(60),
	"descricao" varchar(60),
	"email" varchar(60),
	"idcidade" text,
	"idestado" text,
	"idpais" text,
	"inscricaoestadual" varchar(20),
	"logradouro" varchar(60),
	"numero" varchar(60),
	"razaosocialnome" varchar(60),
	"telefone" varchar(40),
	"tipopessoa" smallint,
	"tipotelefone" smallint
);
--> statement-breakpoint
CREATE TABLE "motiborebaixa" (
	"id" text PRIMARY KEY NOT NULL,
	"idempresa" text NOT NULL,
	"codigo" varchar(6),
	"nome" varchar(50),
	"datacadastro" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"dataultimaalteracao" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"inativo" smallint
);
--> statement-breakpoint
CREATE TABLE "ncm" (
	"id" text PRIMARY KEY NOT NULL,
	"idempresa" text NOT NULL,
	"codigo" varchar(10),
	"codigoexcecao" varchar(3),
	"currenttimemillis" bigint,
	"descricao" text,
	"idnaturezaoperacaoestado" text,
	"idtabelamva" text,
	"inativo" smallint,
	"modalidadebcicmsst" smallint,
	"percentualimpostoaproximado" numeric(5, 2),
	"percentualmva" numeric(5, 2),
	"percentualreducaomva" numeric(5, 2),
	"percimpostoaproximportacao" numeric(5, 2),
	"tipo" smallint
);
--> statement-breakpoint
CREATE TABLE "objeto" (
	"id" text PRIMARY KEY NOT NULL,
	"idempresa" text NOT NULL,
	"codigo" varchar(20),
	"anofabricacao" smallint,
	"campochave" varchar(50),
	"descricao" varchar(100),
	"inativo" smallint,
	"marca" varchar(30),
	"modelo" varchar(30),
	"numerofabricacao" varchar(30),
	"placa" varchar(10),
	"renavam" varchar(11),
	"identidade" text,
	"extra1" text,
	"extra2" text,
	"extra3" text,
	"extra4" text,
	"extra5" text,
	"extra6" text,
	"extra7" text,
	"extra8" text,
	"extra9" text,
	"extra10" text
);
--> statement-breakpoint
CREATE TABLE "operacaofiscal" (
	"id" text PRIMARY KEY NOT NULL,
	"idempresa" text NOT NULL,
	"adicionarpiscofinsinfcomp" smallint,
	"codigocfopservicog2ka" varchar(1),
	"conferencianotafiscal" smallint,
	"conferenciapedido" smallint,
	"consideradevolucaovenda" smallint,
	"considerainscricaoestadualsub" smallint,
	"considerarproduto" smallint,
	"considerarservico" smallint,
	"consideravenda" smallint,
	"consignacao" smallint,
	"consignacaoentrada" smallint,
	"consumidorfinal" smallint,
	"currenttimemillis" bigint,
	"digitarimpostositemnotasaida" smallint,
	"exigirdocumentoreferenciado" smallint,
	"exportacao" smallint,
	"finalidadeemissaonfe" smallint,
	"fundamentacaolegalestado" varchar(100),
	"habilitabaseipiitemnota" smallint,
	"habilitabasepiscofinsitemnota" smallint,
	"idajustedocfiscalcreditoicms" text,
	"idcondicaopagamento" text,
	"idobslancfiscalcreditoicms" text,
	"idplanocontas" text,
	"idtipodocumentofinanceiro" text,
	"importacao" smallint,
	"informartotaismanualmente" smallint,
	"integracao" smallint,
	"naoconsideratribespecproduto" smallint,
	"nome" varchar(40),
	"permitirbaixarlotevencido" smallint,
	"presencaconsumidor" smallint,
	"regimeespecial" smallint,
	"somarcofinsoutrasdesp" smallint,
	"somardespacesoutrasdesp" smallint,
	"somaricmsoutrasdesp" smallint,
	"somarpisoutrasdesp" smallint,
	"somarsiscomexoutrasdesp" smallint,
	"tipovalorpreco" smallint
);
--> statement-breakpoint
CREATE TABLE "ordemservico" (
	"id" text PRIMARY KEY NOT NULL,
	"idempresa" text NOT NULL,
	"agendamento" timestamp(3),
	"anofabricacao" smallint,
	"aprovacaoorcamento" date,
	"caracteristicas" varchar(50),
	"ccf" integer,
	"cnpjcpfcliente" varchar(18),
	"cnpjfilial" varchar(18),
	"codigo" bigint,
	"compra" date,
	"coo" integer,
	"cooger" integer,
	"currenttimemillis" bigint,
	"data" timestamp(3),
	"datahoraimpressao" timestamp(3),
	"datahoraretirada" timestamp(3),
	"dataos" date,
	"dataultimoevento" timestamp(3),
	"descontosubtotal" numeric(12, 2),
	"descricaoitem" text,
	"descricaotipoultimoevento" text,
	"descricaoultimoevento" text,
	"descsubtotalproduto" numeric(12, 2),
	"descsubtotalservico" numeric(12, 2),
	"deslocamento" varchar(50),
	"ecfmarca" varchar(20),
	"ecfmfadicional" varchar(1),
	"ecfmodelo" varchar(20),
	"ecfserie" varchar(20),
	"ecftipo" varchar(7),
	"entradaitem" timestamp(3),
	"existeevento" smallint,
	"extra1" text,
	"extra2" text,
	"extra3" text,
	"extra4" text,
	"extra5" text,
	"extra6" text,
	"extra7" text,
	"extra8" text,
	"extra9" text,
	"extra10" text,
	"extra11" text,
	"extra12" text,
	"extra13" text,
	"extra14" text,
	"extra15" text,
	"extra16" text,
	"faturouparacupom" smallint,
	"faturouparanota" smallint,
	"fimservico" timestamp(3),
	"garantia" smallint,
	"geroufinanceiro" smallint,
	"hash" bigint,
	"hashpafnfce" bigint,
	"idarea" text,
	"idatendente" text,
	"idcliente" text,
	"idcondicaopagamento" text,
	"iddavos" text,
	"iddocumentofiscal" text,
	"idfilial" text,
	"idobjeto" text,
	"idorcamentofaturamento" text,
	"idosmesclada" text,
	"idosorigem" text,
	"idprioridade" text,
	"idproduto" text,
	"idrepresentante2" text,
	"idtipodocumentofinanceiro" text,
	"idtipoproblema" text,
	"idultimotecnico" text,
	"idusuario" text,
	"idusuarioaprovacaoorcamento" text,
	"idusuarioentrega" text,
	"idusuarioliberouatraso" text,
	"idusuarioliberoulimite" text,
	"impresso" smallint,
	"inicioservico" timestamp(3),
	"laudotecnico" text,
	"localatendimento" smallint,
	"marca" varchar(30),
	"modelo" varchar(30),
	"nomecliente" varchar(60),
	"nomeresponsavelretirada" text,
	"numerofabricacao" varchar(30),
	"numeronotafiscal" varchar(20),
	"observacao" text,
	"observacaogarantia" text,
	"orcamento" smallint,
	"orcamentoaprovado" smallint,
	"pautapreco" smallint,
	"pdv" smallint,
	"percdescsubtotalproduto" numeric(5, 2),
	"percdescsubtotalservico" numeric(5, 2),
	"percentualdescontosubtotal" numeric(5, 2),
	"placa" varchar(10),
	"previsaoconclusao" date,
	"problemadescrito" text,
	"renavam" varchar(11),
	"saidaitem" timestamp(3),
	"servicoexecutado" text,
	"serviconaoexecutado" text,
	"status" smallint,
	"tipogarantia" smallint,
	"titulodav" varchar(30),
	"validadegarantia" date,
	"validadeorcamento" date,
	"valor" numeric(12, 2),
	"valorbrinde" numeric(12, 2),
	"valorprodutos" numeric(12, 2),
	"valorservicos" numeric(12, 2)
);
--> statement-breakpoint
CREATE TABLE "prioridades" (
	"id" text PRIMARY KEY NOT NULL,
	"idempresa" text NOT NULL,
	"peso" smallint,
	"inativo" smallint,
	"descricao" varchar(50),
	"codigo" varchar(6),
	"datacadastro" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"dataultimaalteracao" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"idultimousuarioalteracao" text NOT NULL,
	"idusuariocadastro" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "produtos" (
	"id" text PRIMARY KEY NOT NULL,
	"idempresa" text NOT NULL,
	"descricao" varchar(100) NOT NULL,
	"aliquotacofins" numeric(12, 2),
	"aliquotaconfinsentrada" numeric(12, 2),
	"aliquotafcpnf" numeric(12, 2),
	"aliquotaicmsdiferencialentrada" numeric(12, 2),
	"aliquotaicmsinterna" numeric(12, 2),
	"aliquotapis" numeric(12, 2),
	"aliquotapisconfinsentradapreco" numeric(12, 2),
	"aliquotapisconfinssaidapreco" numeric(12, 2),
	"aliquotapisentrada" numeric(12, 2),
	"aliquotareducaoicmsnfcesat" numeric(12, 2),
	"alteraprecopdv" integer,
	"alturashop" numeric(12, 2),
	"anofabricacao" integer,
	"anomodelofabricacao" integer,
	"atualizacaopreco" date,
	"baseicmsconhecimento" numeric(12, 2),
	"baseipiultimanota" numeric(12, 2),
	"basepiscofinsconhecimento" numeric(12, 2),
	"basepiscofinsentradapreco" numeric(12, 2),
	"caminhoicone" varchar,
	"caminhoimagem" varchar,
	"cest" integer,
	"cfopvendaecf" integer,
	"codigo" integer,
	"comissao" numeric(12, 2),
	"comissaoavista" numeric(12, 2),
	"comissaoprazo" numeric(12, 2),
	"cstcofins" numeric(12, 2),
	"cstcofinsentrada" numeric(12, 2),
	"cstpis" numeric(12, 2),
	"cstpisentrada" numeric(12, 2),
	"cstservico" numeric(12, 2),
	"custoalteradopor" text,
	"custoaquisicao" numeric(12, 2),
	"custoindireto" numeric(12, 2),
	"customedioinicial" numeric(12, 2),
	"customediopendente" numeric(12, 2),
	"custovariavelgestaopreco" numeric(12, 2),
	"dataalteracao" date,
	"dataalteracaopreco" date,
	"dataultimacompra" date,
	"datacadastro" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"diferencialicmsgestaocusto" numeric(12, 2),
	"diferidoicmsentrada" numeric(12, 2),
	"ean" integer,
	"eantributavel" integer,
	"endereco" text,
	"fatorconversao" numeric(12, 2),
	"fatorconversaoalternativo" numeric(12, 2),
	"fatorconversaoproducao" numeric(12, 2),
	"fatorconversaounidadeetq" numeric(12, 2),
	"fcpstentrada" numeric(12, 2),
	"fornecedor" text,
	"freteconhecimento" numeric(12, 2),
	"fretegratismercadolivre" integer,
	"freteoutrasdespesas" numeric(12, 2),
	"funrural" integer,
	"icmsconhecimento" numeric(12, 2),
	"icmsentrada" numeric(12, 2),
	"icmssaida" numeric(12, 2),
	"icmsstentrada" numeric(12, 2),
	"icone" text,
	"idbasecalculocredito" text,
	"idbeneficiofiscalnf" text,
	"idbeneficiofiscaloperacao" text,
	"idcest" text,
	"idcfopcontroleperda" text,
	"idcfopentrada" text,
	"idcfopentradadevolucaoexterna" text,
	"idcfopentradadevolucaointerna" text,
	"idcfopentradaexterna" text,
	"idcfopentradatransfexterna" text,
	"idcfopentradatransfinterna" text,
	"idunidademedida" text,
	"idgrupo" text,
	"preco" numeric(12, 2),
	"iat" char(1),
	"referencia" varchar(60),
	"inativo" integer DEFAULT 0,
	"idcfopsaida" text,
	"idcfopsaidadevolucaoexterna" text,
	"idcfopsaidadevolucaointerna" text,
	"idcfopsaidaexterna" text,
	"idcfopsaidaexternanaocontrib" text,
	"idcfopsaidanfce" text,
	"idcfopsaidatransfexterna" text,
	"idcfopsaidatransfinterna" text,
	"idclassificacaofiscal" text,
	"idcomprador" text,
	"idcontribuicaoprevidenciaria" text,
	"idcontribuicaosocialapurada" text,
	"idcontribuicaosocialapurcofins" text,
	"idcreditoestimulado" text,
	"iddepartamento" text,
	"idenquadramentoipientrada" text,
	"idenquadramentoipisaida" text,
	"identificaconsumidor" text,
	"idfabricante" text,
	"idfornecedor" text,
	"idmotivorebaixa" text,
	"idncm" text,
	"idplanocontas" text,
	"idreceitasemcontribuicao" text,
	"imagem" text,
	"ipi" numeric(12, 2),
	"ipientrada" numeric(12, 2),
	"ipiultimanota" numeric(12, 2),
	"ippt" varchar(1),
	"kit" integer,
	"modalidadeicmsst" integer,
	"modocalculoipi" integer,
	"modocalculoipientrada" integer,
	"modocalculopreco" integer,
	"motivodesoneracaoicms" integer,
	"motivodesoneracaonf" integer,
	"ncm" varchar(10),
	"nome" varchar(120) NOT NULL,
	"nomeecf" varchar(120),
	"numerofci" varchar(36),
	"observacoes" text,
	"opcional" integer,
	"origem" integer,
	"origemcusto" integer,
	"outrasdespesasgestaopreco" numeric(5, 2),
	"outrosimpostoscusto" numeric(15, 6),
	"outrosvalorescredgestaocusto" numeric(5, 2),
	"outrosvaloresdebgestaocusto" numeric(5, 2),
	"pedevendedor" integer,
	"percentualfcpentrada" numeric(15, 6),
	"percentualfcpstentrada" numeric(15, 6),
	"percentualfreteoutrasdespesas" numeric(15, 6),
	"percentualipisaida" numeric(5, 2),
	"percentuallucroajustado" numeric(12, 2),
	"percentualreducaoicms" numeric(7, 4),
	"percentualreducaomva" numeric(5, 2),
	"percoutrosvalorespreco" numeric(5, 2),
	"percredbasepiscofinsentrada" numeric(5, 2),
	"percredbasepiscofinssaida" numeric(5, 2),
	"pesavel" integer,
	"peso" numeric(12, 2),
	"podeserbrinde" integer,
	"precoultimacompra" numeric(12, 2),
	"quantidademaxima" integer,
	"quantidademinima" integer,
	"quantidadepadrao" integer,
	"situacaotributariasn" varchar(3),
	"situacaotributariasnentrada" varchar(3),
	"tipo" varchar(1),
	"tipofatorconversaounidadeetq" integer,
	"tipoporcao" integer,
	"tipoproduto" varchar(2),
	"tipoquantidade" integer,
	"tributacao" varchar(7),
	"tributacaoespecial" varchar(7),
	"tributacaoespecialnfcesat" varchar(3),
	"tributacaosn" varchar(3),
	"ultimaaliquotafcpst" numeric(12, 2),
	"ultimaaliquotaicmsst" numeric(12, 2),
	"ultimabasefcpst" numeric(12, 2),
	"ultimodescontonotaentrada" numeric(12, 2),
	"ultimovalorfcpst" numeric(12, 2),
	"ultimovaloricmsst" numeric(12, 2),
	"ultimovaloricmssubstituto" numeric(12, 2),
	"unidademedida" varchar(6),
	"valoricmsdiferencialentrada" numeric(12, 2),
	"valoricmsst" numeric(12, 2),
	"valoripiultimanota" numeric(12, 2),
	"valorlancamentospedcusto" numeric(12, 2),
	"valorlancamentospedcustodebito" numeric(12, 2),
	"venderpeloprecototal" integer
);
--> statement-breakpoint
CREATE TABLE "receitasemcontribuicao" (
	"id" text PRIMARY KEY NOT NULL,
	"idempresa" text NOT NULL,
	"aliquotacofins" numeric(5, 2),
	"aliquotaapis" numeric,
	"codigo" varchar(16),
	"cst" varchar(2),
	"datacadastro" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"dataultimaalteracao" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"descricao" varchar(100),
	"datafinal" date,
	"datainicial" date,
	"descricaounidade" varchar(127),
	"exipi" varchar(256),
	"ncm" varchar(256),
	"ncmex" varchar(256)
);
--> statement-breakpoint
CREATE TABLE "tipoproblema" (
	"id" text PRIMARY KEY NOT NULL,
	"idempresa" text NOT NULL,
	"codigo" varchar(6),
	"descricao" varchar(50),
	"inativo" smallint,
	"datacadastro" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"dataultimaalteracao" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"idultimousuarioalteracao" text NOT NULL,
	"idusuariocadastro" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "unidademedida" (
	"id" text PRIMARY KEY NOT NULL,
	"idempresa" text NOT NULL,
	"casasdecimais" smallint,
	"codigo" varchar(6),
	"currenttimemillis" bigint,
	"nome" varchar(50),
	"tipovalor" smallint
);
--> statement-breakpoint
ALTER TABLE "contacorrentelancamento" ALTER COLUMN "idlancamentotransferencia" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "financeiro" ALTER COLUMN "idorigem" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "financeiro" ALTER COLUMN "idtipodocumentofinanceiro" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "financeiro" ALTER COLUMN "idcontageraboleto" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "financeiro" ALTER COLUMN "idtipocobranca" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "financeiro" ALTER COLUMN "idrepresentante" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "financeiro" ALTER COLUMN "idportador" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "financeiro" ALTER COLUMN "idcarteirageradauboleto" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "financeiro" ALTER COLUMN "iddependente" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "financeiro" ALTER COLUMN "idadministradora" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "financeiro" ALTER COLUMN "idbandeira" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "financeiro" ALTER COLUMN "idrepresentante2" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "planocontas" ALTER COLUMN "idcontacontabilintegracao" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "planocontas" ALTER COLUMN "idgrupodre" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "area" ADD CONSTRAINT "area_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "cest" ADD CONSTRAINT "cest_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "cfop" ADD CONSTRAINT "cfop_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "cfop" ADD CONSTRAINT "cfop_idplanocontas_fkey" FOREIGN KEY ("idplanocontas") REFERENCES "public"."planocontas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "cfop" ADD CONSTRAINT "cfop_idtipodocumentofinanceiro_fkey" FOREIGN KEY ("idtipodocumentofinanceiro") REFERENCES "public"."tipodocumentofinanceiro"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "cfop" ADD CONSTRAINT "cfop_idoperacaofiscal_fkey" FOREIGN KEY ("idoperacaofiscal") REFERENCES "public"."operacaofiscal"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "cfoppadrao" ADD CONSTRAINT "cfoppadrao_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "condicaopagamento" ADD CONSTRAINT "condicaopagamento_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "dav" ADD CONSTRAINT "dav_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "dav" ADD CONSTRAINT "fk_dav_cliente" FOREIGN KEY ("idcliente") REFERENCES "public"."entidade"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "dav" ADD CONSTRAINT "fk_dav_representante" FOREIGN KEY ("idrepresentante") REFERENCES "public"."entidade"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "dav" ADD CONSTRAINT "fk_dav_representante2" FOREIGN KEY ("idrepresentante2") REFERENCES "public"."entidade"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "dav" ADD CONSTRAINT "fk_dav_transp" FOREIGN KEY ("idtransportadora") REFERENCES "public"."entidade"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "dav" ADD CONSTRAINT "fk_dav_entremessaecommerce" FOREIGN KEY ("identidaderemessaecommerce") REFERENCES "public"."entidade"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "dav" ADD CONSTRAINT "fk_dav_condicaopagamento" FOREIGN KEY ("idcondicaopagamento") REFERENCES "public"."condicaopagamento"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "dav" ADD CONSTRAINT "fk_dav_tipodocumentofinanceiro" FOREIGN KEY ("idtipodocumentofinanceiro") REFERENCES "public"."tipodocumentofinanceiro"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "dav" ADD CONSTRAINT "fk_dav_cfop" FOREIGN KEY ("idcfop") REFERENCES "public"."cfop"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "dav" ADD CONSTRAINT "fk_dav_contadeposito" FOREIGN KEY ("idcontacorrentedeposito") REFERENCES "public"."contacorrente"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "dav" ADD CONSTRAINT "fk_dav_contapix" FOREIGN KEY ("idcontacorrentepix") REFERENCES "public"."contacorrente"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "dav" ADD CONSTRAINT "fk_dav_davgerada" FOREIGN KEY ("iddavgerada") REFERENCES "public"."dav"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "dav" ADD CONSTRAINT "fk_dav_davmesclada" FOREIGN KEY ("iddavmesclada") REFERENCES "public"."dav"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "dav" ADD CONSTRAINT "fk_dav_davoriginal" FOREIGN KEY ("iddavoriginal") REFERENCES "public"."dav"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "dav" ADD CONSTRAINT "fk_dav_usuario" FOREIGN KEY ("idusuario") REFERENCES "public"."usuarios"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "dav" ADD CONSTRAINT "fk_dav_usuariofaturamento" FOREIGN KEY ("idusuariofaturamento") REFERENCES "public"."usuarios"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "dav" ADD CONSTRAINT "fk_dav_usuario_desc_fin" FOREIGN KEY ("idusuariodescontofin") REFERENCES "public"."usuarios"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "dav" ADD CONSTRAINT "fk_dav_usuario_cancel" FOREIGN KEY ("idusuariocancelamento") REFERENCES "public"."usuarios"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "dav" ADD CONSTRAINT "fk_dav_idusuarioconferencia" FOREIGN KEY ("idusuarioconferencia") REFERENCES "public"."usuarios"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "departamento" ADD CONSTRAINT "departamento_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "departamento" ADD CONSTRAINT "departamento_idultimousuarioalteracao_fkey" FOREIGN KEY ("idultimousuarioalteracao") REFERENCES "public"."usuarios"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "departamento" ADD CONSTRAINT "departamento_idusuariocadastro_fkey" FOREIGN KEY ("idusuariocadastro") REFERENCES "public"."usuarios"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "enquatramentoipi" ADD CONSTRAINT "enquatramentoipi_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "hierarquia" ADD CONSTRAINT "hierarquia_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "hierarquia" ADD CONSTRAINT "fk_hierarquia_cest" FOREIGN KEY ("idcest") REFERENCES "public"."cest"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "hierarquia" ADD CONSTRAINT "fk_hierarquia_comprador" FOREIGN KEY ("idcomprador") REFERENCES "public"."entidade"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "localretirada" ADD CONSTRAINT "localretirada_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "motiborebaixa" ADD CONSTRAINT "motiborebaixa_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "ncm" ADD CONSTRAINT "ncm_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "objeto" ADD CONSTRAINT "objeto_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "objeto" ADD CONSTRAINT "objeto_identidade_fkey" FOREIGN KEY ("identidade") REFERENCES "public"."entidade"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "operacaofiscal" ADD CONSTRAINT "operacaofiscal_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "operacaofiscal" ADD CONSTRAINT "fk_operacaofiscal_planocontas" FOREIGN KEY ("idplanocontas") REFERENCES "public"."planocontas"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "operacaofiscal" ADD CONSTRAINT "fk_operacaofiscal_tipdocfin" FOREIGN KEY ("idtipodocumentofinanceiro") REFERENCES "public"."tipodocumentofinanceiro"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "ordemservico" ADD CONSTRAINT "ordemservico_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "ordemservico" ADD CONSTRAINT "fk_ordemservico_entidade" FOREIGN KEY ("idcliente") REFERENCES "public"."entidade"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "ordemservico" ADD CONSTRAINT "fk_ordemservico_representante2" FOREIGN KEY ("idrepresentante2") REFERENCES "public"."entidade"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "ordemservico" ADD CONSTRAINT "fk_ordemservico_atendente" FOREIGN KEY ("idatendente") REFERENCES "public"."entidade"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "ordemservico" ADD CONSTRAINT "fk_ordemservico_ultimo_tecnico" FOREIGN KEY ("idultimotecnico") REFERENCES "public"."entidade"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "ordemservico" ADD CONSTRAINT "fk_ordemservico_produto" FOREIGN KEY ("idproduto") REFERENCES "public"."produtos"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "ordemservico" ADD CONSTRAINT "fk_ordemservico_tipodocfin" FOREIGN KEY ("idtipodocumentofinanceiro") REFERENCES "public"."tipodocumentofinanceiro"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "ordemservico" ADD CONSTRAINT "fk_ordemservico_osmesclada" FOREIGN KEY ("idosmesclada") REFERENCES "public"."ordemservico"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "ordemservico" ADD CONSTRAINT "fk_ordemservico_osorigem" FOREIGN KEY ("idosorigem") REFERENCES "public"."ordemservico"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "ordemservico" ADD CONSTRAINT "fk_ordemservico_usuario_cad" FOREIGN KEY ("idusuario") REFERENCES "public"."usuarios"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "ordemservico" ADD CONSTRAINT "fk_ordemservico_usuaprovorc" FOREIGN KEY ("idusuarioaprovacaoorcamento") REFERENCES "public"."usuarios"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "ordemservico" ADD CONSTRAINT "fk_ordemservico_usuario" FOREIGN KEY ("idusuarioentrega") REFERENCES "public"."usuarios"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "prioridades" ADD CONSTRAINT "prioridades_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "produtos" ADD CONSTRAINT "produtos_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "produtos" ADD CONSTRAINT "produtos_fornecedor_fkey" FOREIGN KEY ("fornecedor") REFERENCES "public"."entidade"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "produtos" ADD CONSTRAINT "produtos_idcomprador_fkey" FOREIGN KEY ("idcomprador") REFERENCES "public"."entidade"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "produtos" ADD CONSTRAINT "produtos_idcfopcontroleperda_fkey" FOREIGN KEY ("idcfopcontroleperda") REFERENCES "public"."cfop"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "produtos" ADD CONSTRAINT "produtos_idcfopsaidanfce_fkey" FOREIGN KEY ("idcfopsaidanfce") REFERENCES "public"."cfop"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "produtos" ADD CONSTRAINT "produtos_idcfopentrada_fkey" FOREIGN KEY ("idcfopentrada") REFERENCES "public"."cfop"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "produtos" ADD CONSTRAINT "produtos_idcfopsaida_fkey" FOREIGN KEY ("idcfopsaida") REFERENCES "public"."cfop"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "produtos" ADD CONSTRAINT "produtos_idcfopentradadevolucaoexterna_fkey" FOREIGN KEY ("idcfopentradadevolucaoexterna") REFERENCES "public"."cfop"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "produtos" ADD CONSTRAINT "produtos_idcfopentradadevolucaointerna_fkey" FOREIGN KEY ("idcfopentradadevolucaointerna") REFERENCES "public"."cfop"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "produtos" ADD CONSTRAINT "produtos_idcfopentradaexterna_fkey" FOREIGN KEY ("idcfopentradaexterna") REFERENCES "public"."cfop"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "produtos" ADD CONSTRAINT "produtos_idcfopentradatransfexterna_fkey" FOREIGN KEY ("idcfopentradatransfexterna") REFERENCES "public"."cfop"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "produtos" ADD CONSTRAINT "produtos_idcfopentradatransfinterna_fkey" FOREIGN KEY ("idcfopentradadevolucaointerna") REFERENCES "public"."cfop"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "produtos" ADD CONSTRAINT "produtos_idplanocontas_fkey" FOREIGN KEY ("idplanocontas") REFERENCES "public"."planocontas"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "produtos" ADD CONSTRAINT "produtos_idncm_fkey" FOREIGN KEY ("idncm") REFERENCES "public"."ncm"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "produtos" ADD CONSTRAINT "produtos_idcest_fkey" FOREIGN KEY ("idcest") REFERENCES "public"."cest"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "produtos" ADD CONSTRAINT "produtos_idunidademedida_fkey" FOREIGN KEY ("idunidademedida") REFERENCES "public"."unidademedida"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "produtos" ADD CONSTRAINT "produtos_idgrupo_fkey" FOREIGN KEY ("idgrupo") REFERENCES "public"."hierarquia"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "produtos" ADD CONSTRAINT "produtos_idreceitasemcontribuicao_fkey" FOREIGN KEY ("idreceitasemcontribuicao") REFERENCES "public"."receitasemcontribuicao"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "receitasemcontribuicao" ADD CONSTRAINT "receitasemcontribuicao_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "tipoproblema" ADD CONSTRAINT "tipoproblema_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "tipoproblema" ADD CONSTRAINT "tipoproblema_idultimousuarioalteracao_fkey" FOREIGN KEY ("idultimousuarioalteracao") REFERENCES "public"."usuarios"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "tipoproblema" ADD CONSTRAINT "tipoproblema_idusuariocadastro_fkey" FOREIGN KEY ("idusuariocadastro") REFERENCES "public"."usuarios"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "unidademedida" ADD CONSTRAINT "unidademedida_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
CREATE INDEX "area_idempresa_idx" ON "area" USING btree ("idempresa" text_ops);--> statement-breakpoint
CREATE INDEX "cest_idempresa_idx" ON "cest" USING btree ("idempresa" text_ops);--> statement-breakpoint
CREATE INDEX "cfop_idempresa_idx" ON "cfop" USING btree ("idempresa" text_ops);--> statement-breakpoint
CREATE INDEX "cfoppadrao_idempresa_idx" ON "cfoppadrao" USING btree ("idempresa" text_ops);--> statement-breakpoint
CREATE INDEX "condicaopagamento_idempresa_idx" ON "condicaopagamento" USING btree ("idempresa" text_ops);--> statement-breakpoint
CREATE INDEX "condicaopagamento_codigo_idx" ON "condicaopagamento" USING btree ("codigo" text_ops);--> statement-breakpoint
CREATE INDEX "dav_idempresa_idx" ON "dav" USING btree ("idempresa" text_ops);--> statement-breakpoint
CREATE INDEX "dav_codigo_idx" ON "dav" USING btree ("codigo" int8_ops);--> statement-breakpoint
CREATE INDEX "enquatramentoipi_idempresa_idx" ON "enquatramentoipi" USING btree ("idempresa" text_ops);--> statement-breakpoint
CREATE INDEX "hierarquia_idempresa_idx" ON "hierarquia" USING btree ("idempresa" text_ops);--> statement-breakpoint
CREATE INDEX "localretirada_idempresa_idx" ON "localretirada" USING btree ("idempresa" text_ops);--> statement-breakpoint
CREATE INDEX "motiborebaixa_idempresa_idx" ON "motiborebaixa" USING btree ("idempresa" text_ops);--> statement-breakpoint
CREATE INDEX "motiborebaixa_codigo_idx" ON "motiborebaixa" USING btree ("codigo" text_ops);--> statement-breakpoint
CREATE INDEX "ncm_idempresa_idx" ON "ncm" USING btree ("idempresa" text_ops);--> statement-breakpoint
CREATE INDEX "ncm_codigo_idx" ON "ncm" USING btree ("codigo" text_ops);--> statement-breakpoint
CREATE INDEX "objeto_idempresa_idx" ON "objeto" USING btree ("idempresa" text_ops);--> statement-breakpoint
CREATE INDEX "operacaofiscal_idempresa_idx" ON "operacaofiscal" USING btree ("idempresa" text_ops);--> statement-breakpoint
CREATE INDEX "ordemservico_idempresa_idx" ON "ordemservico" USING btree ("idempresa" text_ops);--> statement-breakpoint
CREATE INDEX "ordemservico_codigo_idx" ON "ordemservico" USING btree ("codigo" int8_ops);--> statement-breakpoint
CREATE INDEX "prioridades_idempresa_idx" ON "prioridades" USING btree ("idempresa" text_ops);--> statement-breakpoint
CREATE INDEX "tipoproblema_idempresa_idx" ON "tipoproblema" USING btree ("idempresa" text_ops);--> statement-breakpoint
CREATE INDEX "unidademedida_idempresa_idx" ON "unidademedida" USING btree ("idempresa" text_ops);--> statement-breakpoint
CREATE INDEX "unidademedida_codigo_idx" ON "unidademedida" USING btree ("codigo" text_ops);--> statement-breakpoint
ALTER TABLE "assinaturas" ADD CONSTRAINT "assinaturas_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "assinaturas" ADD CONSTRAINT "assinaturas_idassinaturaasaas_fkey" FOREIGN KEY ("idassinaturaasaas") REFERENCES "public"."clientes_asaas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "clientes_asaas" ADD CONSTRAINT "clientes_asaas_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "contacorrente" ADD CONSTRAINT "contacorrent_idempresa.fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "contacorrente" ADD CONSTRAINT "contacorrent_idbanco.fkey" FOREIGN KEY ("idbanco") REFERENCES "public"."banco"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "contacorrente" ADD CONSTRAINT "contacorrent_identidade.fkey" FOREIGN KEY ("identidade") REFERENCES "public"."entidade"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "contacorrente" ADD CONSTRAINT "contacorrent_idcontacontabilintegracao.fkey" FOREIGN KEY ("idcontacontabilintegracao") REFERENCES "public"."contacontabil"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "contacorrentelancamento" ADD CONSTRAINT "contacorrentelancamento_idcontacorrente_fkey" FOREIGN KEY ("idcontacorrente") REFERENCES "public"."contacorrente"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "contacorrentelancamento" ADD CONSTRAINT "contacorrentelancamento_idusuario_fkey" FOREIGN KEY ("idusuario") REFERENCES "public"."usuarios"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contacorrentelancamento" ADD CONSTRAINT "contacorrentelancamento_idplanocontas_fkey" FOREIGN KEY ("idplanocontas") REFERENCES "public"."planocontas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "contacorrentelancamento" ADD CONSTRAINT "contacorrentelancamento_idlancamentotransferencia_fkey" FOREIGN KEY ("idlancamentotransferencia") REFERENCES "public"."contacorrentelancamento"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "contacorrentelancamento" ADD CONSTRAINT "contacorrentelancamento_idusuarioconciliacao_fkey" FOREIGN KEY ("idusuarioconciliacao") REFERENCES "public"."usuarios"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "contacorrentelancamento" ADD CONSTRAINT "contacorrentelancamento_idlancamentoestornado_fkey" FOREIGN KEY ("idlancamentoestornado") REFERENCES "public"."contacorrentelancamento"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "contas" ADD CONSTRAINT "contas_idusuario_fkey" FOREIGN KEY ("idusuario") REFERENCES "public"."usuarios"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "financeiro" ADD CONSTRAINT "financeiro_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "financeiro" ADD CONSTRAINT "financeiro_identidade_fkey" FOREIGN KEY ("identidade") REFERENCES "public"."entidade"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "financeiro" ADD CONSTRAINT "financeiro_idtipodocumentofinanceiro_fkey" FOREIGN KEY ("idtipodocumentofinanceiro") REFERENCES "public"."tipodocumentofinanceiro"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "financeirolancamento" ADD CONSTRAINT "financeirolancamento_idfinanceiro_fkey" FOREIGN KEY ("idfinanceiro") REFERENCES "public"."financeiro"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "financeirolancamento" ADD CONSTRAINT "financeirolancamento_evento_fkey" FOREIGN KEY ("idplanocontasacrescimo") REFERENCES "public"."planocontas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "financeirolancamento" ADD CONSTRAINT "financeirolancamento_idplanocontasdesconto_fkey" FOREIGN KEY ("idplanocontasdesconto") REFERENCES "public"."planocontas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "financeirolancamento" ADD CONSTRAINT "financeirolancamento_idplanocontasmulta_fkey" FOREIGN KEY ("idplanocontasmulta") REFERENCES "public"."planocontas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "financeirolancamento" ADD CONSTRAINT "financeirolancamento_idplanocontasjuros_fkey" FOREIGN KEY ("idplanocontasjuros") REFERENCES "public"."planocontas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "motivobaixafinanceiro" ADD CONSTRAINT "motivobaixafinanceiro_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notificacoes" ADD CONSTRAINT "notificacoes_idusuario_fkey" FOREIGN KEY ("idusuario") REFERENCES "public"."usuarios"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notificacoes" ADD CONSTRAINT "notificacoes_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "planocontas" ADD CONSTRAINT "planocontas_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "sessoes" ADD CONSTRAINT "sessoes_idusuario_fkey" FOREIGN KEY ("idusuario") REFERENCES "public"."usuarios"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "tipodocumentofinanceiro" ADD CONSTRAINT "tipodocumentofinanceiro_idempresa_fkey" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "tipodocumentofinanceiro" ADD CONSTRAINT "tipodocumentofinanceiro_idmotivobaixafinanceiro_fkey" FOREIGN KEY ("idmotivobaixafinanceiro") REFERENCES "public"."motivobaixafinanceiro"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
CREATE INDEX "audit_logs_idusuario_idx" ON "audit_logs" USING btree ("idusuario");--> statement-breakpoint
CREATE INDEX "audit_logs_idempresa_idx" ON "audit_logs" USING btree ("idempresa");--> statement-breakpoint
CREATE INDEX "banco_idempresa_idx" ON "banco" USING btree ("idempresa" text_ops);--> statement-breakpoint
CREATE INDEX "contacontabil_idempresa_idx" ON "contacontabil" USING btree ("idempresa" text_ops);--> statement-breakpoint
CREATE INDEX "contacontabil_idcontapai_idx" ON "contacontabil" USING btree ("idcontapai" text_ops);--> statement-breakpoint
CREATE INDEX "contacontabil_idultimousuarioalteracao_idx" ON "contacontabil" USING btree ("idultimousuarioalteracao" text_ops);--> statement-breakpoint
CREATE INDEX "contacontabil_idusuariocadastro_idx" ON "contacontabil" USING btree ("idusuariocadastro" text_ops);--> statement-breakpoint
CREATE INDEX "planocontas_idempresa_idx" ON "planocontas" USING btree ("idempresa" text_ops);--> statement-breakpoint
CREATE INDEX "planocontascontacontabil_idempresa_idx" ON "planocontascontacontabil" USING btree ("idempresa" text_ops);--> statement-breakpoint
CREATE INDEX "usuario_empresas_idusuario_idx" ON "usuario_empresas" USING btree ("idusuario");--> statement-breakpoint
CREATE INDEX "usuario_empresas_idempresa_idx" ON "usuario_empresas" USING btree ("idempresa");