CREATE TABLE "custoproduto" (
	"id" text PRIMARY KEY NOT NULL,
	"adicional" numeric(21, 10) DEFAULT '0',
	"casasdecimais" smallint,
	"currenttimemillis" bigint,
	"datahora" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"idcustoorigem" text,
	"iddesmontagem" text,
	"idfilial" text,
	"idmotivorebaixa" text,
	"idnotafiscal" text,
	"idproduto" text NOT NULL,
	"idregistroproducao" text,
	"idultimousuario" text,
	"importadopatch" smallint,
	"observacaorebaixa" text,
	"origem" smallint,
	"percentualdiferencialicms" numeric(5, 2),
	"status" smallint,
	"tipocalculoicms" smallint,
	"tipocalculopiscofins" smallint
);
--> statement-breakpoint
CREATE TABLE "notafiscal" (
	"id" text PRIMARY KEY NOT NULL,
	"idempresa" text NOT NULL,
	"acrescimocancelamento" numeric(12, 2),
	"acrescimoservicos" numeric(12, 2),
	"acrescimosproduto" numeric(12, 2),
	"acrescimosubtotal" numeric(12, 2),
	"agenciabancocheque" varchar(10),
	"aliquotacofinsconhecimento" numeric(12, 2),
	"aliquotaicms" numeric(12, 2),
	"aliquotapisconhecimento" numeric(12, 2),
	"alterado" smallint,
	"aprazo" numeric(12, 2),
	"arquivoxmlassinado" text,
	"arquivoxmlautorizada" text,
	"arquivoxmlcancelada" text,
	"arquivoxmlconsultasituacao" text,
	"arquivoxmlcontingencia" text,
	"arquivoxmldenegada" text,
	"arquivoxmleventoepec" text,
	"arquivoxmlnotaoriginal" text,
	"avista" numeric(12, 2),
	"bairro" varchar(50),
	"bairroentrega" varchar(50),
	"bairroobra" varchar(60),
	"basecalculoicmsdifal" numeric(12, 2),
	"basecofinsretido" numeric(12, 2),
	"basecontribuicaosocial" numeric(12, 2),
	"basefcpstanterior" numeric(12, 2),
	"baseicms" numeric(12, 2),
	"baseicmsdiferido" numeric(12, 2),
	"baseicmsefetivo" numeric(12, 2),
	"baseicmsnaoaproveitado" numeric(12, 2),
	"baseicmsstanterior" numeric(12, 2),
	"baseicmssubstituicao" numeric(12, 2),
	"baseimpostorenda" numeric(12, 2),
	"baseinss" numeric(12, 2),
	"baseiss" numeric(12, 2),
	"basepiscofinsconhecimento" numeric(12, 2),
	"basepisretido" numeric(12, 2),
	"canceladoporevento" smallint,
	"cancelamento" timestamp(3),
	"carteiradigital" numeric(12, 2),
	"celularentrega" varchar(40),
	"cep" varchar(9),
	"cepentrega" varchar(9),
	"cepobra" varchar(9),
	"cfopconhecimentotransporte" varchar(5),
	"chavedocumentoreferenciado" varchar(44),
	"chavenfe" varchar(44),
	"cheque" numeric(12, 2),
	"cidade" varchar(50),
	"cidadetransportadora" varchar(50),
	"classeconsumoagua" varchar(2),
	"classeconsumocomunicacao" varchar(2),
	"classeconsumoenergia" varchar(2),
	"classeconsumogas" varchar(2),
	"cnpjcpf" varchar(20),
	"cnpjcpfentrega" varchar(18),
	"cnpjcpftransportadora" varchar(18),
	"cnpjemissor" varchar(14),
	"codigoantecipacaotributaria" smallint,
	"codigoautenticidadenfse" varchar(255),
	"codigoexportador" varchar(60),
	"codigostatusprotocolonfe" smallint,
	"codigostatustransmissaonfe" smallint,
	"cofins" numeric(12, 2),
	"cofinsretido" numeric(12, 2),
	"complemento" varchar(50),
	"complementoentrega" varchar(60),
	"complementolocalobra" varchar(255),
	"conferencia" smallint,
	"conferenciafinanceira" smallint,
	"conferenciafisica" smallint,
	"consignacaogerada" smallint,
	"consumidorfinal" smallint,
	"consumoagua" varchar(2),
	"consumoenergia" varchar(2),
	"contrato" varchar(60),
	"contribuicaosocial" numeric(12, 2),
	"coodocumentoreferenciado" integer,
	"cpfcnpjautorizadoxml" varchar(20),
	"cpfcnpjemitentecheque" varchar(20),
	"csticmsconhecimento" varchar(3),
	"csticmssnconhecimento" varchar(3),
	"cstpiscofinsconhecimento" varchar(2),
	"currenttimemillis" bigint,
	"dataalteracao" timestamp(3),
	"dataconfcega" timestamp(3),
	"dataconffinanceira" timestamp(3),
	"datacontingencia" varchar(10),
	"datadesembaraco" date,
	"datadi" date,
	"datadocumentoreferenciado" date,
	"dataemissaonotaprodutor" date,
	"dataextemporanea" date,
	"datahoraconsultasituacao" timestamp(3),
	"datahoraemissao" timestamp(3),
	"datahoraentradasaida" timestamp(3),
	"datahoransu" timestamp(3),
	"datainclusao" timestamp(3),
	"datapedido" date,
	"datapreparacao" date,
	"datavencimentocontrato" date,
	"deposito" numeric(12, 2),
	"descontoproduto" numeric(12, 2),
	"descontoservicos" numeric(12, 2),
	"descontosubtotal" numeric(12, 2),
	"descricaocfop" varchar(1024),
	"despesasimportacao" numeric(12, 2),
	"devolucao" numeric(12, 2),
	"devolucaoautomatica" smallint,
	"diafaturamentocontrato" smallint,
	"dinheiro" numeric(12, 2),
	"documentoorigem" bigint,
	"ecfseriedocumentoreferenciado" varchar(20),
	"emailentrega" varchar(60),
	"emissao" date,
	"endereco" varchar(60),
	"enderecoentrega" varchar(60),
	"enderecotransportadora" varchar(50),
	"entradasaida" date,
	"especie" varchar(60),
	"estado" char(2),
	"estadotransportadora" char(2),
	"estadoveiculo" char(2),
	"extra" numeric(12, 2),
	"finalidadeemissaonfe" smallint,
	"financiado" numeric(12, 2),
	"formaemissaonfe" smallint,
	"formaintermedioimportacao" smallint,
	"frete" numeric(12, 2),
	"funrural" numeric(12, 2),
	"hash" bigint,
	"horacontingencia" varchar(8),
	"horasaida" time,
	"icms" numeric(12, 2),
	"icmsdestino" numeric(12, 2),
	"icmsdiferido" numeric(12, 2),
	"icmsfundopobreza" numeric(12, 2),
	"icmsfundopobrezainterno" numeric(12, 2),
	"icmsfundopobrezainternonaoapro" numeric(12, 2),
	"icmsfundopobrezast" numeric(12, 2),
	"icmsnaoaproveitado" numeric(12, 2),
	"icmsremetente" numeric(12, 2),
	"icmssubstituicao" numeric(12, 2),
	"idadmcarteiradigital" text,
	"idbancocheque" text,
	"idbasecalculocredito" text,
	"idbeneficiador" text,
	"idcfop" text,
	"idcidade" text,
	"idcidadedestinoconhec" text,
	"idcidadeentrega" text,
	"idcidadeobra" text,
	"idcidadeorigemconhec" text,
	"idcidadeprestacaoservico" text,
	"idcidadetransportadora" text,
	"idclientedobeneficiador" text,
	"idcondicaopagto" text,
	"idcontacorrentedeposito" text,
	"idcontacorrentepix" text,
	"iddocumentoconsignacao" text,
	"identidade" text,
	"identidadefilialanterior" text,
	"idestado" text,
	"idestadodesembaraco" text,
	"idestadodestinoconhec" text,
	"idestadoentrega" text,
	"idestadoobra" text,
	"idestadoorigemconhec" text,
	"idestadoprestacaoservico" text,
	"idestadosaidapais" text,
	"idestadotransportadora" text,
	"idestadoveiculo" text,
	"idfilial" text,
	"idintermediadormarketplace" text,
	"idlocalestoque" text,
	"idlocalestoqueentradatransf" text,
	"idlocalestoquesaidatransf" text,
	"idlocalretirada" text,
	"idmotivodesconto" text,
	"idnotadesagregacaoinsumos" text,
	"idnotaentradaconsignacao" text,
	"idnotafiscaltransfdestino" text,
	"idnotafiscalvendaexpedicao" text,
	"idnotarelacionadaconhecimento" text,
	"idoperacao" text,
	"idoperacaofiscal" text,
	"idpais" text,
	"idplanocontas" text,
	"idrepresentante" text,
	"idrepresentante2" text,
	"idserie" text,
	"idtipocredito" text,
	"idtipodocumento" text,
	"idtransacaofinanceira" text,
	"idtransportadora" text,
	"idusuarioalteracao" text,
	"idusuarioconfcega" text,
	"idusuarioconffinanceira" text,
	"idusuarioinclusao" text,
	"idusuarioliberouatraso" text,
	"idusuarioliberoulimite" text,
	"ietransportadora" varchar(20),
	"impostoaproximado" numeric(12, 2),
	"impostoimportacao" numeric(12, 2),
	"impostorenda" numeric(12, 2),
	"impresso" smallint,
	"indacrescimosubtotal" varchar(1),
	"inddescontosubtotal" varchar(1),
	"indicadornaturezafrete" smallint,
	"infocompgerada" text,
	"infocomppersonalizada" text,
	"infofisco" text,
	"infofiscogerada" text,
	"inscricaoestadual" varchar(20),
	"inss" numeric(12, 2),
	"ipi" numeric(12, 2),
	"iss" numeric(12, 2),
	"justificativacancelamentonfe" varchar(255),
	"latitude" numeric(10, 7),
	"latitudeentrega" numeric(10, 7),
	"linknfse" varchar(255),
	"localdesembaraco" varchar(60),
	"localdespacho" varchar(60),
	"localsaidapais" varchar(60),
	"logradouroobra" varchar(255),
	"longitude" numeric(10, 7),
	"longitudeentrega" numeric(10, 7),
	"marca" varchar(60),
	"mediaaliquotacofinsincentivado" numeric(12, 2),
	"mediaaliquotaicmsincentivado" numeric(12, 2),
	"mediaaliquotapisincentivado" numeric(12, 2),
	"mensagemprotocolonfe" text,
	"mensagemtransmissaonfe" text,
	"modelo" varchar(4),
	"modelodocumentoreferenciado" varchar(10),
	"modelonotaprodutor" varchar(2),
	"motivocontingencia" varchar(256),
	"nomeemitentecheque" varchar(60),
	"nometransportadora" varchar(60),
	"notadesagregacaoinsumos" smallint,
	"notaempenho" varchar(22),
	"nsu" integer,
	"numero" varchar(60),
	"numeroart" varchar(20),
	"numerocei" varchar(20),
	"numerocheque" varchar(20),
	"numerocontacorrentebancocheque" varchar(10),
	"numerodi" varchar(12),
	"numerodocumentoreferenciado" varchar(11),
	"numerodrawback" varchar(20),
	"numeroendereco" varchar(6),
	"numeroenderecoentrega" varchar(6),
	"numeroenderecotransportadora" varchar(6),
	"numerolotecancelamento" integer,
	"numeroloteenvio" integer,
	"numeromatricula" varchar(20),
	"numeronfse" varchar(20),
	"numeronotafiscal" varchar(11),
	"numeronotaprodutor" varchar(9),
	"numeroobra" varchar(20),
	"numeroprojeto" varchar(20),
	"numeroserienotaprodutor" varchar(3),
	"observacao" text,
	"ordemdescontoacrescimo" varchar(1),
	"origemprincipal" integer,
	"outrasdespesas" numeric(12, 2),
	"outros" numeric(12, 2),
	"pautapreco" smallint,
	"pdvdocumentoreferenciado" smallint,
	"pedido" varchar(60),
	"pendenciarps" smallint,
	"percentualcomissaofaturamento" numeric(5, 2),
	"percentualcomissaofaturamento2" numeric(5, 2),
	"percentualcomissaoquitacao" numeric(5, 2),
	"percentualcomissaoquitacao2" numeric(5, 2),
	"percentualdescontosubtotal" numeric(5, 2),
	"percentualredbaseicmsconhec" numeric(5, 2),
	"pesobruto" numeric(12, 3),
	"pesoliquido" numeric(12, 3),
	"pis" numeric(12, 2),
	"pisretido" numeric(12, 2),
	"pix" numeric(12, 2),
	"placaveiculo" varchar(8),
	"posaprazo" numeric(12, 2),
	"posavista" numeric(12, 2),
	"possuicartacorrecao" smallint,
	"precopendente" smallint,
	"presencaconsumidor" smallint,
	"proprio" smallint,
	"protocoloepec" varchar(50),
	"protocolonfe" varchar(18),
	"quantidade" numeric(15, 6),
	"razaosocial" varchar(60),
	"razaosocialnomeentrega" varchar(60),
	"recebimentonfe" varchar(30),
	"recibotransmissaonfe" varchar(18),
	"retencaoiss" numeric(12, 2),
	"seguro" numeric(12, 2),
	"serie" varchar(6),
	"seriedocumentoreferenciado" varchar(6),
	"status" smallint,
	"statusconsignacaoentrada" smallint,
	"statusdesagregacao" char(1),
	"taxasiscomex" numeric(12, 2),
	"telefone" varchar(40),
	"telefoneentrega" varchar(40),
	"tipoambientenfe" smallint,
	"tipoassinante" varchar(2),
	"tipocontribuinte" smallint,
	"tipocte" varchar(2),
	"tipodocumento" varchar(2),
	"tipodocumentoconsignacao" smallint,
	"tipodocumentoimportacao" smallint,
	"tipodocumentopaf" varchar(1),
	"tipoemissao" char(1),
	"tipofrete" smallint,
	"tipoligacao" varchar(2),
	"tiponotadocumentoreferenciado" varchar(3),
	"tipoorigem" smallint,
	"tiporateiocentrocusto" smallint,
	"tiporateioconhecimento" smallint,
	"tipotelefone" smallint,
	"tipotensao" varchar(2),
	"tipoviatransporteinternacional" smallint,
	"totalproduto" numeric(12, 2),
	"totalservicos" numeric(12, 2),
	"transferencia" smallint,
	"transferenciaentradaautomatica" smallint,
	"valorafrmm" numeric(12, 2),
	"valorcofinsincentivado" numeric(12, 2),
	"valorfcpstanterior" numeric(12, 2),
	"valoricmsdesoneradosemdesconto" numeric(12, 2),
	"valoricmsefetivo" numeric(12, 2),
	"valoricmsincentivado" numeric(12, 2),
	"valoricmsstanterior" numeric(12, 2),
	"valorimpostosincentivados" numeric(12, 2),
	"valorpisincentivado" numeric(12, 2),
	"valortotalnota" numeric(12, 2),
	"valorvendor" numeric(12, 2),
	"vencimentocheque" date
);
--> statement-breakpoint
CREATE TABLE "notafiscalitem" (
	"id" text PRIMARY KEY NOT NULL,
	"acrescimo" numeric(12, 2),
	"aliquotacofins" numeric(12, 4),
	"aliquotacofinsretido" numeric(5, 2),
	"altura" numeric(10, 2),
	"anofabricacao" smallint,
	"anomodelofabricacao" smallint,
	"aplicaprecocalculado" smallint,
	"cfop" varchar(20),
	"chassi" varchar(17),
	"chaveibpt" varchar(6),
	"chavenfe" varchar(44),
	"chavenferecebidaexportacao" varchar(44),
	"cilindrada" varchar(4),
	"classificacaofiscal" varchar(8),
	"cm3" varchar(4),
	"cmkg" varchar(9),
	"cmvatual" numeric(15, 6),
	"cnpjconcessionaria" varchar(18),
	"cnpjemissor" varchar(14),
	"codigobeneficiofiscal" varchar(10),
	"codigolistalc11603" varchar(5),
	"codigomarcamodelo" numeric(7, 0),
	"condicaoveiculo" smallint,
	"contador" smallint,
	"cor" varchar(4),
	"cordenatran" varchar(2),
	"cstcofins" varchar(2),
	"cstpis" varchar(2),
	"currenttimemillis" bigint,
	"datahoraretirada" timestamp(3),
	"datalote" date,
	"dataprogramacaopreco" date,
	"decimaispreco" smallint,
	"decimaisquantidade" smallint,
	"descontoclienteprodutoaplicado" smallint,
	"descricao" varchar(120),
	"descricaoarma" varchar(256),
	"descricaocor" varchar(40),
	"detalhenfe" text,
	"distanciaeixos" varchar(4),
	"emissao" date,
	"entidadenotafiscalterceiros" varchar(60),
	"enviartagsdiferimentototal" smallint,
	"especieveiculo" smallint,
	"fonteibpt" varchar(50),
	"gerarcreditoicmsst" smallint,
	"gerarcreditoipi" smallint,
	"hash" bigint,
	"icmsstinformadomanualmente" smallint,
	"idajustedocumentofiscal" text,
	"idativoimobilizado" text,
	"idbasecalculocredito" text,
	"idbeneficiofiscal" text,
	"idcfop" text,
	"idcontribuicaosocialapurada" text,
	"idcontribuicaosocialapurcofins" text,
	"iddavitem" text,
	"iddevolucaoitem" text,
	"idembalagem" text,
	"idembalagemtributavel" text,
	"idenquadramentoipi" text,
	"identidadedesconto" text,
	"idestadoconcessionaria" text,
	"idfilialretiradaentrega" text,
	"idlote" text,
	"idmotivodesconto" text,
	"idmotivorebaixa" text,
	"idncm" text,
	"idnotafiscal" text NOT NULL,
	"idnotafiscalitemdevolvido" text,
	"idnotafiscalitemterceiros" text,
	"idnotafiscalitemtranscompra" text,
	"idnotafiscalitemtransfsaida" text,
	"idobservacaolancamentofiscal" text,
	"idpedidocompraitem" text,
	"idproduto" text,
	"idprodutobase" text,
	"idprodutokit" text,
	"idpromocao" text,
	"idreceitasemcontribuicao" text,
	"idrepresentante2" text,
	"idrequisicaotransferenciaitem" text,
	"idsupervisorvenda" text,
	"idtipocredito" text,
	"idunidademedida" text,
	"idunidademedidatributavel" text,
	"idusuariodesconto" text,
	"idusuarioretirada" text,
	"informacaoadicional" varchar(500),
	"itemorigempossuicofins" smallint,
	"itemorigempossuiicms" smallint,
	"itemorigempossuiipi" smallint,
	"itemorigempossuipis" smallint,
	"itempeps" smallint,
	"lotacao" smallint,
	"lote" varchar(30),
	"marcaveiculo" varchar(20),
	"modalidadeicmsst" smallint,
	"modocalculoipi" smallint,
	"modocalculopreco" smallint,
	"motivodesoneracaocofins" smallint,
	"motivodesoneracaoicms" smallint,
	"motivodesoneracaoicmssemdesc" smallint,
	"motivodesoneracaopis" smallint,
	"naoconsiderarvalortotalnota" smallint,
	"naopossuiicmsstnotaorigem" smallint,
	"ncm" varchar(11),
	"numerodrawback" varchar(20),
	"numeroitempedidocompra" varchar(6),
	"numeromotor" varchar(21),
	"numeronotafiscal" varchar(11),
	"numeronotafiscalterceiros" varchar(11),
	"numeropedidocompra" varchar(15),
	"numeroregistroexportacao" varchar(12),
	"numeroseriearma" varchar(15),
	"numeroseriecanoarma" varchar(15),
	"observacao" varchar(20),
	"observacaorebaixa" text,
	"origem" smallint,
	"pautapreco" smallint,
	"percentualicmsaproveitamento" numeric(7, 4),
	"percentualreducaoicms" numeric(9, 6),
	"pesobrutoveiculo" varchar(9),
	"pesoliquidoveiculo" varchar(9),
	"placaveiculo" varchar(8),
	"potenciamotor" varchar(4),
	"precificado" smallint,
	"produto" varchar(20),
	"produtoespecifico" smallint,
	"quantidadehora" varchar(5),
	"quantidadepeca" bigint,
	"quantidadetributavel" numeric(15, 4),
	"referenciafornecedor" varchar(60),
	"renavam" varchar(11),
	"replicarcusto" smallint,
	"replicarformacao" smallint,
	"reterpiscofins" smallint,
	"retirado" smallint,
	"serial" varchar(9),
	"serie" varchar(4),
	"situacaotributaria" varchar(3),
	"situacaotributariadigitada" varchar(3),
	"situacaotributariaipi" varchar(3),
	"situacaotributariasn" varchar(3),
	"statusprecoitem" smallint,
	"statusremessaterceiros" smallint,
	"tipo" char(1),
	"tipoarma" smallint,
	"tipocombustivel" varchar(8),
	"tipodocumentopaf" varchar(1),
	"tipokit" smallint,
	"tipooperacao" smallint,
	"tipopintura" varchar(1),
	"tiporestricao" smallint,
	"tiporetiradaentregaitem" smallint,
	"tipotinta" smallint,
	"tipovalordesconto" smallint,
	"tipovaloricms" smallint,
	"tipovaloripi" smallint,
	"tipoveiculo" smallint,
	"totalizadorparcial" varchar(10),
	"tributacao" varchar(7),
	"tributacaoespecial" varchar(7),
	"unidade" varchar(6),
	"unidademedidaxml" varchar(6),
	"veiculonovo" smallint,
	"vim" varchar(1)
);
--> statement-breakpoint
ALTER TABLE "custoproduto" ADD CONSTRAINT "fk_custo_prod" FOREIGN KEY ("idproduto") REFERENCES "public"."produtos"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "custoproduto" ADD CONSTRAINT "fk_custo_custoorigem" FOREIGN KEY ("idcustoorigem") REFERENCES "public"."custoproduto"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "custoproduto" ADD CONSTRAINT "fk_custo_motivorebaixa" FOREIGN KEY ("idmotivorebaixa") REFERENCES "public"."motiborebaixa"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "custoproduto" ADD CONSTRAINT "fk_custo_ultimousuario" FOREIGN KEY ("idultimousuario") REFERENCES "public"."usuarios"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscal" ADD CONSTRAINT "fk_notafiscal_empresa" FOREIGN KEY ("idempresa") REFERENCES "public"."empresas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscal" ADD CONSTRAINT "fk_notafiscal_entidade" FOREIGN KEY ("identidade") REFERENCES "public"."entidade"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscal" ADD CONSTRAINT "fk_notafiscal_representante" FOREIGN KEY ("idrepresentante") REFERENCES "public"."entidade"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscal" ADD CONSTRAINT "fk_notafiscal_representante2" FOREIGN KEY ("idrepresentante2") REFERENCES "public"."entidade"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscal" ADD CONSTRAINT "fk_notafiscal_cfop" FOREIGN KEY ("idcfop") REFERENCES "public"."cfop"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscal" ADD CONSTRAINT "fk_notafiscal_transportadora" FOREIGN KEY ("idtransportadora") REFERENCES "public"."entidade"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscal" ADD CONSTRAINT "fk_notafiscal_condicaopag" FOREIGN KEY ("idcondicaopagto") REFERENCES "public"."condicaopagamento"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscal" ADD CONSTRAINT "fk_notafiscal_tipdocfinanceiro" FOREIGN KEY ("idtipodocumento") REFERENCES "public"."tipodocumentofinanceiro"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscal" ADD CONSTRAINT "fk_notafiscal_usuarioinclusao" FOREIGN KEY ("idusuarioinclusao") REFERENCES "public"."usuarios"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscal" ADD CONSTRAINT "fk_notafiscal_usuarioalteracao" FOREIGN KEY ("idusuarioalteracao") REFERENCES "public"."usuarios"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscal" ADD CONSTRAINT "fk_notafiscal_notafiscalconhec" FOREIGN KEY ("idnotarelacionadaconhecimento") REFERENCES "public"."notafiscal"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscal" ADD CONSTRAINT "fk_notafiscal_nfentradaconsig" FOREIGN KEY ("idnotaentradaconsignacao") REFERENCES "public"."notafiscal"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscal" ADD CONSTRAINT "fk_notafiscal_operacaofiscal" FOREIGN KEY ("idoperacaofiscal") REFERENCES "public"."operacaofiscal"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscal" ADD CONSTRAINT "fk_notafiscal_usuarioconffin" FOREIGN KEY ("idusuarioconffinanceira") REFERENCES "public"."usuarios"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscal" ADD CONSTRAINT "fk_notafiscal_usuarioconfcega" FOREIGN KEY ("idusuarioconfcega") REFERENCES "public"."usuarios"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscal" ADD CONSTRAINT "fk_notafiscal_nfentradadesins" FOREIGN KEY ("idnotadesagregacaoinsumos") REFERENCES "public"."notafiscal"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscal" ADD CONSTRAINT "fk_entidade_beneficiador" FOREIGN KEY ("idbeneficiador") REFERENCES "public"."entidade"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscal" ADD CONSTRAINT "fk_entidade_cliente_benef" FOREIGN KEY ("idclientedobeneficiador") REFERENCES "public"."entidade"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscal" ADD CONSTRAINT "fk_nf_nftransf" FOREIGN KEY ("idnotafiscaltransfdestino") REFERENCES "public"."notafiscal"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscal" ADD CONSTRAINT "fk_nf_nfvendaexpedicao" FOREIGN KEY ("idnotafiscalvendaexpedicao") REFERENCES "public"."notafiscal"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscal" ADD CONSTRAINT "fk_nf_contadeposito" FOREIGN KEY ("idcontacorrentedeposito") REFERENCES "public"."contacorrente"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscal" ADD CONSTRAINT "fk_nf_contapix" FOREIGN KEY ("idcontacorrentepix") REFERENCES "public"."contacorrente"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscal" ADD CONSTRAINT "fk_nf_local_ret" FOREIGN KEY ("idlocalretirada") REFERENCES "public"."localretirada"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscal" ADD CONSTRAINT "fk_notafiscal_planocontas" FOREIGN KEY ("idplanocontas") REFERENCES "public"."planocontas"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscalitem" ADD CONSTRAINT "fk_notafiscalitem_notafiscal" FOREIGN KEY ("idnotafiscal") REFERENCES "public"."notafiscal"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscalitem" ADD CONSTRAINT "fk_notafiscalitem_produto" FOREIGN KEY ("idproduto") REFERENCES "public"."produtos"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscalitem" ADD CONSTRAINT "fk_notafiscalitem_produtokit" FOREIGN KEY ("idprodutokit") REFERENCES "public"."produtos"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscalitem" ADD CONSTRAINT "fk_notafiscalitem_cfop" FOREIGN KEY ("idcfop") REFERENCES "public"."cfop"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscalitem" ADD CONSTRAINT "fk_nfitem_ncm" FOREIGN KEY ("idncm") REFERENCES "public"."ncm"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscalitem" ADD CONSTRAINT "fk_nfitem_unidademedida" FOREIGN KEY ("idunidademedida") REFERENCES "public"."unidademedida"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscalitem" ADD CONSTRAINT "fk_nfitem_unidademedida_trib" FOREIGN KEY ("idunidademedidatributavel") REFERENCES "public"."unidademedida"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscalitem" ADD CONSTRAINT "fk_notafiscalitem_motrebaixa" FOREIGN KEY ("idmotivorebaixa") REFERENCES "public"."motiborebaixa"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscalitem" ADD CONSTRAINT "fk_nfitem_usuariodesconto" FOREIGN KEY ("idusuariodesconto") REFERENCES "public"."usuarios"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscalitem" ADD CONSTRAINT "fk_nfitem_usuariopreco" FOREIGN KEY ("idsupervisorvenda") REFERENCES "public"."usuarios"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscalitem" ADD CONSTRAINT "fk_nfitem_usuario_retirada" FOREIGN KEY ("idusuarioretirada") REFERENCES "public"."usuarios"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscalitem" ADD CONSTRAINT "fk_nfitem_nfi_terc" FOREIGN KEY ("idnotafiscalitemterceiros") REFERENCES "public"."notafiscalitem"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notafiscalitem" ADD CONSTRAINT "fk_nfitem_nfi_dev" FOREIGN KEY ("idnotafiscalitemdevolvido") REFERENCES "public"."notafiscalitem"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
CREATE INDEX "notafiscal_idempresa_idx" ON "notafiscal" USING btree ("idempresa" text_ops);--> statement-breakpoint
CREATE INDEX "notafiscal_identidade_idx" ON "notafiscal" USING btree ("identidade" text_ops);--> statement-breakpoint
CREATE INDEX "notafiscal_idfilial_idx" ON "notafiscal" USING btree ("idfilial" text_ops);--> statement-breakpoint
CREATE INDEX "notafiscal_chavenfe_idx" ON "notafiscal" USING btree ("chavenfe" text_ops);--> statement-breakpoint
CREATE INDEX "notafiscalitem_idnotafiscal_idx" ON "notafiscalitem" USING btree ("idnotafiscal" text_ops);--> statement-breakpoint
CREATE INDEX "notafiscalitem_idproduto_idx" ON "notafiscalitem" USING btree ("idproduto" text_ops);