import type { Icon } from "@tabler/icons-react";
import {
	IconArrowsLeftRight,
	IconBuilding,
	IconBuildingBank,
	IconCashBanknoteMinus,
	IconCashBanknotePlus,
	IconCashRegister,
	IconChartBar,
	IconCreditCard,
	IconDashboard,
	IconFileInvoice,
	IconHelp,
	IconHistory,
	IconListDetails,
	IconReportMoney,
	IconSettings,
	IconUser,
	IconUsers,
} from "@tabler/icons-react";

export interface SearchablePage {
	title: string;
	url: string;
	category: string;
	icon?: Icon;
	keywords?: string[];
	mobileOnly?: boolean;
}

export const SEARCHABLE_PAGES: SearchablePage[] = [
	// Principal
	{
		title: "Dashboard",
		url: "/dashboard",
		category: "Principal",
		icon: IconDashboard,
		keywords: ["início", "home", "painel"],
	},
	{
		title: "PDV Gourmet — Mesas",
		url: "/gourmet",
		category: "Gourmet",
		icon: IconCashRegister,
		keywords: ["pdv", "gourmet", "mesa", "mesas", "comanda", "restaurante"],
	},
	{
		title: "Garçom",
		url: "/garcom",
		category: "Gourmet",
		icon: IconUser,
		keywords: ["garçom", "garcom", "pedido", "comanda", "mobile", "mesa"],
		mobileOnly: true,
	},
	{
		title: "Venda rápida",
		url: "/pdv",
		category: "PDV",
		icon: IconCashRegister,
		keywords: ["pdv", "venda", "rápida", "balcão", "caixa"],
	},
	{
		title: "Histórico de vendas",
		url: "/vendas-pdv",
		category: "PDV",
		icon: IconHistory,
		keywords: ["pdv", "vendas", "histórico", "historico"],
	},
	{
		title: "Fechamentos de caixa",
		url: "/fechamentos-caixa",
		category: "PDV",
		icon: IconHistory,
		keywords: ["pdv", "caixa", "fechamento", "fechamentos"],
	},
	{
		title: "Clientes",
		url: "/clientes",
		category: "Principal",
		icon: IconUsers,
		keywords: ["cliente", "clientes"],
	},
	// {
	// 	title: "Comissionados",
	// 	url: "/comissionados",
	// 	category: "Principal",
	// 	icon: IconUser,
	// 	keywords: ["comissionado", "comissionados"],
	// },
	// {
	// 	title: "Compradores",
	// 	url: "/compradores",
	// 	category: "Principal",
	// 	icon: IconUsers,
	// 	keywords: ["comprador", "compradores"],
	// },
	{
		title: "Fornecedores",
		url: "/fornecedores",
		category: "Principal",
		icon: IconBuilding,
		keywords: ["fornecedor", "fornecedores"],
	},
	{
		title: "Produtos",
		url: "/produtos",
		category: "Principal",
		icon: IconListDetails,
		keywords: ["produto", "produtos", "item"],
	},
	{
		title: "Grupos",
		url: "/grupos",
		category: "Principal",
		icon: IconListDetails,
		keywords: ["hierarquia", "hierarquias", "grupo", "grupos", "produto"],
	},
	{
		title: "Unidades de medida",
		url: "/unidade-medida",
		category: "Principal",
		icon: IconListDetails,
		keywords: ["unidade", "medida", "unidades", "kg", "litro"],
	},
	{
		title: "Fatores de conversão",
		url: "/fator-conversao",
		category: "Principal",
		icon: IconListDetails,
		keywords: ["fator", "conversão", "conversao", "unidade", "quantidade"],
	},
	{
		title: "Naturezas de operação",
		url: "/tributos/naturezas",
		category: "Tributos",
		icon: IconListDetails,
		keywords: ["cfop", "fiscal", "entrada", "saída", "natureza", "tributos"],
	},
	{
		title: "Configuração fiscal",
		url: "/tributos/configuracao-fiscal",
		category: "Tributos",
		icon: IconListDetails,
		keywords: ["regime", "simples", "lucro", "tributário", "fiscal"],
	},
	{
		title: "CFOP de-para",
		url: "/tributos/cfop-depara",
		category: "Tributos",
		icon: IconListDetails,
		keywords: ["cfop", "de-para", "entrada", "saída", "mapeamento"],
	},
	{
		title: "Tributos",
		url: "/tributos",
		category: "Tributos",
		icon: IconListDetails,
		keywords: ["tributos", "fiscal", "impostos"],
	},
	{
		title: "Usuários",
		url: "/usuarios",
		category: "Principal",
		icon: IconUser,
		keywords: ["usuário", "usuarios", "user"],
	},
	{
		title: "Nota fiscal de compra",
		url: "/nota-fiscal-compra",
		category: "Financeiro",
		icon: IconFileInvoice,
		keywords: ["nota fiscal", "nota-fiscal", "compra", "entrada"],
	},
	{
		title: "Nota fiscal de venda",
		url: "/nota-fiscal-venda",
		category: "Financeiro",
		icon: IconFileInvoice,
		keywords: ["nota fiscal", "nota-fiscal", "venda", "saída"],
	},
	{
		title: "Nota fiscal de serviço",
		url: "/nota-fiscal-servico",
		category: "Financeiro",
		icon: IconFileInvoice,
		keywords: ["nfse", "nfs-e", "serviço", "rps"],
	},
	// Financeiro
	{
		title: "Plano de contas",
		url: "/plano-contas",
		category: "Financeiro",
		icon: IconListDetails,
		keywords: ["plano", "contas", "conta"],
	},
	{
		title: "Bancos",
		url: "/bancos",
		category: "Financeiro",
		icon: IconBuildingBank,
		keywords: ["banco", "bancos", "instituição financeira"],
	},
	{
		title: "Contas correntes",
		url: "/contas-correntes",
		category: "Financeiro",
		icon: IconCreditCard,
		keywords: ["conta corrente", "conta", "corrente"],
	},
	{
		title: "Movimentações",
		url: "/movimentacoes",
		category: "Financeiro",
		icon: IconArrowsLeftRight,
		keywords: ["movimentação", "movimentacoes", "transação", "transações"],
	},
	{
		title: "Importar OFX",
		url: "/movimentacoes/importar-ofx",
		category: "Financeiro",
		icon: IconArrowsLeftRight,
		keywords: ["ofx", "extrato", "importar", "banco", "movimentação"],
	},
	{
		title: "Contas a receber",
		url: "/contas-receber",
		category: "Financeiro",
		icon: IconCashBanknotePlus,
		keywords: ["receber", "recebimento", "recebimentos", "a receber"],
	},
	{
		title: "Contas a pagar",
		url: "/contas-pagar",
		category: "Financeiro",
		icon: IconCashBanknoteMinus,
		keywords: ["pagar", "pagamento", "pagamentos", "a pagar"],
	},
	{
		title: "Relatórios",
		url: "/relatorios",
		category: "Financeiro",
		icon: IconChartBar,
		keywords: ["relatório", "relatorios", "relatorio", "report"],
	},
	// Contabilidade
	{
		title: "Configuração",
		url: "/configuracao-contabilidade",
		category: "Contabilidade",
		icon: IconReportMoney,
		keywords: ["configuração", "configuracao", "config", "contabilidade"],
	},
	{
		title: "Integração contábil",
		url: "/integracao-contabil",
		category: "Contabilidade",
		icon: IconReportMoney,
		keywords: ["integração", "integracao", "integracao contabil", "contábil"],
	},
	{
		title: "Código reduzidos",
		url: "/codigo-reduzidos",
		category: "Contabilidade",
		icon: IconReportMoney,
		keywords: ["código", "codigo", "reduzido", "reduzidos"],
	},
	{
		title: "Plano de contas contábeis",
		url: "/conta-contabil",
		category: "Contabilidade",
		icon: IconReportMoney,
		keywords: ["plano contas contábeis", "contábeis", "contabeis"],
	},
	{
		title: "Exportar XMLs fiscais",
		url: "/contabilidade/exportar-xmls",
		category: "Contabilidade",
		icon: IconReportMoney,
		keywords: [
			"xml",
			"xmls",
			"nf-e",
			"nfce",
			"exportar",
			"contabilidade",
			"zip",
		],
	},
	{
		title: "Relatórios fiscais",
		url: "/relatorios/fiscais",
		category: "Relatórios",
		icon: IconChartBar,
		keywords: [
			"relatório",
			"relatorio",
			"contabilidade",
			"fiscal",
			"pdf",
			"consolidado",
		],
	},
	{
		title: "Relatório de compras",
		url: "/relatorios/fiscais/compras",
		category: "Relatórios",
		icon: IconChartBar,
		keywords: ["relatório", "relatorio", "compras", "nf-e entrada", "pdf"],
	},
	{
		title: "Relatório de vendas",
		url: "/relatorios/fiscais/vendas",
		category: "Relatórios",
		icon: IconChartBar,
		keywords: ["relatório", "relatorio", "vendas", "nf-e", "nfce", "pdf"],
	},
	// Outros
	{
		title: "Configurações",
		url: "/configuracoes",
		category: "Outros",
		icon: IconSettings,
		keywords: ["configuração", "configuracao", "config", "settings"],
	},
	{
		title: "Auditoria",
		url: "/auditoria",
		category: "Outros",
		icon: IconHistory,
		keywords: ["auditoria", "audit", "histórico", "historico"],
	},
	{
		title: "Ajuda",
		url: "/ajuda",
		category: "Outros",
		icon: IconHelp,
		keywords: ["ajuda", "help", "suporte", "documentação", "documentacao"],
	},
];
