import type { Icon } from "@tabler/icons-react";
import {
	IconArrowsLeftRight,
	IconBuilding,
	IconBuildingBank,
	IconCashBanknoteMinus,
	IconCashBanknotePlus,
	IconCashRegister,
	IconChartBar,
	IconCreditCard,
	IconDashboard,
	IconFileInvoice,
	IconHelp,
	IconHistory,
	IconListDetails,
	IconPackage,
	IconReportMoney,
	IconScale,
	IconSettings,
	IconUser,
	IconUsers,
} from "@tabler/icons-react";

export interface SearchablePage {
	title: string;
	url: string;
	category: string;
	icon?: Icon;
	keywords?: string[];
	mobileOnly?: boolean;
}

export const SEARCHABLE_PAGES: SearchablePage[] = [
	// Geral
	{
		title: "Dashboard",
		url: "/dashboard",
		category: "Geral",
		icon: IconDashboard,
		keywords: ["início", "home", "painel"],
	},

	// Vendas e operação
	{
		title: "Venda rápida",
		url: "/pdv",
		category: "Vendas e operação",
		icon: IconCashRegister,
		keywords: ["pdv", "venda", "rápida", "balcão", "caixa"],
	},
	{
		title: "Histórico de vendas",
		url: "/vendas-pdv",
		category: "Vendas e operação",
		icon: IconHistory,
		keywords: ["pdv", "vendas", "histórico", "historico"],
	},
	{
		title: "Fechamentos de caixa",
		url: "/fechamentos-caixa",
		category: "Vendas e operação",
		icon: IconHistory,
		keywords: ["pdv", "caixa", "fechamento", "fechamentos"],
	},
	{
		title: "Pedidos da maquininha",
		url: "/pedidos?origem=POS",
		category: "Vendas e operação",
		icon: IconCashRegister,
		keywords: ["pos", "maquininha", "pedidos", "pdv"],
	},
	{
		title: "Pedidos (DAV)",
		url: "/pedidos",
		category: "Vendas e operação",
		icon: IconFileInvoice,
		keywords: ["dav", "pedido", "pedidos", "orçamento", "orcamento"],
	},
	{
		title: "Ordens de serviço",
		url: "/ordens-servico",
		category: "Vendas e operação",
		icon: IconListDetails,
		keywords: ["os", "ordem", "serviço", "servico", "ordens"],
	},
	{
		title: "PDV Gourmet — Mesas",
		url: "/gourmet",
		category: "Vendas e operação",
		icon: IconCashRegister,
		keywords: ["pdv", "gourmet", "mesa", "mesas", "comanda", "restaurante"],
	},
	{
		title: "Garçom",
		url: "/garcom",
		category: "Vendas e operação",
		icon: IconUser,
		keywords: ["garçom", "garcom", "pedido", "comanda", "mobile", "mesa"],
		mobileOnly: true,
	},

	// Cadastros
	{
		title: "Clientes",
		url: "/clientes",
		category: "Cadastros",
		icon: IconUsers,
		keywords: ["cliente", "clientes", "pessoas"],
	},
	{
		title: "Fornecedores",
		url: "/fornecedores",
		category: "Cadastros",
		icon: IconBuilding,
		keywords: ["fornecedor", "fornecedores", "pessoas"],
	},
	{
		title: "Produtos",
		url: "/produtos",
		category: "Cadastros",
		icon: IconListDetails,
		keywords: ["produto", "produtos", "item", "catálogo", "catalogo"],
	},
	{
		title: "Serviços",
		url: "/servicos",
		category: "Cadastros",
		icon: IconListDetails,
		keywords: [
			"serviço",
			"servico",
			"serviços",
			"servicos",
			"iss",
			"nfs-e",
			"catálogo",
			"catalogo",
		],
	},
	{
		title: "Grupos",
		url: "/grupos",
		category: "Cadastros",
		icon: IconListDetails,
		keywords: ["hierarquia", "hierarquias", "grupo", "grupos", "produto"],
	},
	{
		title: "Grupos gourmet",
		url: "/grupos-gourmet",
		category: "Cadastros",
		icon: IconListDetails,
		keywords: ["gourmet", "cozinha", "bar", "mesa", "impressora", "grupo"],
	},
	{
		title: "Unidades de medida",
		url: "/unidade-medida",
		category: "Cadastros",
		icon: IconListDetails,
		keywords: ["unidade", "medida", "unidades", "kg", "litro"],
	},
	{
		title: "Fatores de conversão",
		url: "/fator-conversao",
		category: "Cadastros",
		icon: IconListDetails,
		keywords: ["fator", "conversão", "conversao", "unidade", "quantidade"],
	},
	{
		title: "Meios de pagamento",
		url: "/meios-pagamento",
		category: "Cadastros",
		icon: IconCreditCard,
		keywords: [
			"meio",
			"pagamento",
			"condicao",
			"bandeira",
			"cartao",
			"visa",
			"mastercard",
		],
	},
	{
		title: "Bancos",
		url: "/bancos",
		category: "Cadastros",
		icon: IconBuildingBank,
		keywords: ["banco", "bancos", "instituição financeira"],
	},
	{
		title: "Tipos de problema",
		url: "/tipos-problema",
		category: "Cadastros",
		icon: IconListDetails,
		keywords: ["tipo", "problema", "os", "ordem", "serviço"],
	},

	// Estoque
	{
		title: "Posição de estoque",
		url: "/estoque",
		category: "Estoque",
		icon: IconPackage,
		keywords: ["estoque", "saldo", "posição", "posicao", "inventário", "inventario"],
	},
	{
		title: "Fichas de produção",
		url: "/fichas-producao",
		category: "Estoque",
		icon: IconPackage,
		keywords: [
			"ficha",
			"produção",
			"producao",
			"bom",
			"receita",
			"insumo",
			"fabricacao",
			"fabricação",
		],
	},
	{
		title: "Produções",
		url: "/producoes",
		category: "Estoque",
		icon: IconHistory,
		keywords: ["produção", "producao", "fabricacao", "fabricação", "histórico"],
	},
	{
		title: "Exportar balança (MGV)",
		url: "/ferramentas/exportar-mgv",
		category: "Estoque",
		icon: IconScale,
		keywords: [
			"mgv",
			"toledo",
			"balança",
			"balanca",
			"txtitens",
			"itensmgv",
			"exportar",
			"produtos",
		],
	},

	// Financeiro
	{
		title: "Plano de contas",
		url: "/plano-contas",
		category: "Financeiro",
		icon: IconListDetails,
		keywords: ["plano", "contas", "conta"],
	},
	{
		title: "Cotações de compra",
		url: "/compras/cotacoes",
		category: "Compras",
		icon: IconListDetails,
		keywords: ["cotação", "cotacao", "compra", "fornecedor"],
	},
	{
		title: "Pedidos de compra",
		url: "/compras/pedidos",
		category: "Compras",
		icon: IconListDetails,
		keywords: ["pedido", "compra", "fornecedor"],
	},
	{
		title: "Budget",
		url: "/budget",
		category: "Financeiro",
		icon: IconListDetails,
		keywords: ["budget", "orçamento", "orcamento", "limite", "gastos"],
	},
	{
		title: "Acompanhamento de Budget",
		url: "/budget/acompanhamento",
		category: "Financeiro",
		icon: IconListDetails,
		keywords: [
			"budget",
			"orçamento",
			"orcamento",
			"acompanhamento",
			"previsto",
			"realizado",
		],
	},
	{
		title: "Contas correntes",
		url: "/contas-correntes",
		category: "Financeiro",
		icon: IconCreditCard,
		keywords: ["conta corrente", "conta", "corrente"],
	},
	{
		title: "Movimentações",
		url: "/movimentacoes",
		category: "Financeiro",
		icon: IconArrowsLeftRight,
		keywords: ["movimentação", "movimentacoes", "transação", "transações", "caixa"],
	},
	{
		title: "Importar OFX",
		url: "/movimentacoes/importar-ofx",
		category: "Financeiro",
		icon: IconArrowsLeftRight,
		keywords: ["ofx", "extrato", "importar", "banco", "movimentação"],
	},
	{
		title: "Contas a receber",
		url: "/contas-receber",
		category: "Financeiro",
		icon: IconCashBanknotePlus,
		keywords: ["receber", "recebimento", "recebimentos", "a receber"],
	},
	{
		title: "Contas a pagar",
		url: "/contas-pagar",
		category: "Financeiro",
		icon: IconCashBanknoteMinus,
		keywords: ["pagar", "pagamento", "pagamentos", "a pagar"],
	},
	{
		title: "Relatórios",
		url: "/relatorios",
		category: "Financeiro",
		icon: IconChartBar,
		keywords: ["relatório", "relatorios", "relatorio", "report"],
	},

	// Fiscal e tributário
	{
		title: "Nota fiscal de compra",
		url: "/nota-fiscal-compra",
		category: "Fiscal e tributário",
		icon: IconFileInvoice,
		keywords: ["nota fiscal", "nota-fiscal", "compra", "entrada", "nfe"],
	},
	{
		title: "Nota fiscal de produto",
		url: "/nota-fiscal-venda",
		category: "Fiscal e tributário",
		icon: IconFileInvoice,
		keywords: [
			"nota fiscal",
			"nota-fiscal",
			"venda",
			"saída",
			"numeração",
			"numeracao",
			"próximo número",
			"proximo numero",
			"nfe",
		],
	},
	{
		title: "NFC-e",
		url: "/nfce",
		category: "Fiscal e tributário",
		icon: IconFileInvoice,
		keywords: [
			"nfce",
			"nfc-e",
			"cupom",
			"numeração",
			"numeracao",
			"próximo número",
			"proximo numero",
			"pdv",
		],
	},
	{
		title: "Nota fiscal de serviço",
		url: "/nota-fiscal-servico",
		category: "Fiscal e tributário",
		icon: IconFileInvoice,
		keywords: ["nfse", "nfs-e", "serviço", "rps"],
	},
	{
		title: "Captura SEFAZ",
		url: "/nota-fiscal-compra/captura-sefaz",
		category: "Fiscal e tributário",
		icon: IconFileInvoice,
		keywords: ["sefaz", "captura", "manifestação", "manifestacao"],
	},
	{
		title: "Naturezas de operação",
		url: "/tributos/naturezas",
		category: "Fiscal e tributário",
		icon: IconListDetails,
		keywords: ["cfop", "fiscal", "entrada", "saída", "natureza", "tributos"],
	},
	{
		title: "Configuração fiscal",
		url: "/tributos/configuracao-fiscal",
		category: "Fiscal e tributário",
		icon: IconListDetails,
		keywords: ["regime", "simples", "lucro", "tributário", "fiscal"],
	},
	{
		title: "CFOP de-para",
		url: "/tributos/cfop-depara",
		category: "Fiscal e tributário",
		icon: IconListDetails,
		keywords: ["cfop", "de-para", "entrada", "saída", "mapeamento"],
	},
	{
		title: "Parametrização de tributos",
		url: "/tributos/parametrizacao",
		category: "Fiscal e tributário",
		icon: IconListDetails,
		keywords: ["parametrização", "parametrizacao", "tributos", "icms"],
	},
	{
		title: "Regras fiscais",
		url: "/tributos/regras-fiscais",
		category: "Fiscal e tributário",
		icon: IconListDetails,
		keywords: ["regra fiscal", "st", "difal", "cfop", "vigência", "nfe"],
	},
	{
		title: "Taxas por UF",
		url: "/tributos/taxas",
		category: "Fiscal e tributário",
		icon: IconListDetails,
		keywords: ["taxa", "uf", "alíquota", "aliquota", "icms"],
	},
	{
		title: "Tributos",
		url: "/tributos",
		category: "Fiscal e tributário",
		icon: IconListDetails,
		keywords: ["tributos", "fiscal", "impostos"],
	},

	// Contabilidade
	{
		title: "Configuração",
		url: "/configuracao-contabilidade",
		category: "Contabilidade",
		icon: IconReportMoney,
		keywords: ["configuração", "configuracao", "config", "contabilidade"],
	},
	{
		title: "Integração contábil",
		url: "/configuracoes?tab=integracoes-contabeis",
		category: "Contabilidade",
		icon: IconReportMoney,
		keywords: [
			"integração",
			"integracao",
			"integracao contabil",
			"contábil",
			"domínio",
			"dominio",
			"onvio",
		],
	},
	{
		title: "Códigos reduzidos",
		url: "/codigo-reduzidos",
		category: "Contabilidade",
		icon: IconReportMoney,
		keywords: ["código", "codigo", "reduzido", "reduzidos"],
	},
	{
		title: "Plano de contas contábeis",
		url: "/conta-contabil",
		category: "Contabilidade",
		icon: IconReportMoney,
		keywords: ["plano contas contábeis", "contábeis", "contabeis"],
	},
	{
		title: "Gerar SINTEGRA",
		url: "/contabilidade/sintegra",
		category: "Contabilidade",
		icon: IconReportMoney,
		keywords: ["sintegra", "exportar", "obrigação", "obrigacao", "fiscal"],
	},
	{
		title: "Exportar XMLs fiscais",
		url: "/contabilidade/exportar-xmls",
		category: "Contabilidade",
		icon: IconReportMoney,
		keywords: [
			"xml",
			"xmls",
			"nf-e",
			"nfce",
			"exportar",
			"contabilidade",
			"zip",
		],
	},
	{
		title: "Relatórios fiscais",
		url: "/relatorios/fiscais",
		category: "Contabilidade",
		icon: IconChartBar,
		keywords: [
			"relatório",
			"relatorio",
			"contabilidade",
			"fiscal",
			"pdf",
			"consolidado",
		],
	},
	{
		title: "Relatório de compras",
		url: "/relatorios/fiscais/compras",
		category: "Contabilidade",
		icon: IconChartBar,
		keywords: ["relatório", "relatorio", "compras", "nf-e entrada", "pdf"],
	},
	{
		title: "Relatório de vendas",
		url: "/relatorios/fiscais/vendas",
		category: "Contabilidade",
		icon: IconChartBar,
		keywords: ["relatório", "relatorio", "vendas", "nf-e", "nfce", "pdf"],
	},

	// Administração e sistema
	{
		title: "Usuários",
		url: "/usuarios",
		category: "Administração e sistema",
		icon: IconUser,
		keywords: ["usuário", "usuarios", "user", "permissões", "permissoes"],
	},
	{
		title: "Agendar tarefas",
		url: "/agendamentos",
		category: "Administração e sistema",
		icon: IconSettings,
		keywords: [
			"agendar",
			"agendamento",
			"agendamentos",
			"automação",
			"automacao",
			"tarefa",
			"sintegra",
		],
	},
	{
		title: "Envio de e-mails",
		url: "/envio-emails",
		category: "Administração e sistema",
		icon: IconSettings,
		keywords: ["email", "e-mail", "smtp", "envio"],
	},
	{
		title: "Certificados digitais",
		url: "/certificados-digitais",
		category: "Administração e sistema",
		icon: IconSettings,
		keywords: ["certificado", "a1", "a3", "digital", "nfe"],
	},
	{
		title: "Editor SQL",
		url: "/editor-sql",
		category: "Administração e sistema",
		icon: IconSettings,
		keywords: ["sql", "editor", "consulta", "query", "suporte"],
	},
	{
		title: "Configurações",
		url: "/configuracoes",
		category: "Administração e sistema",
		icon: IconSettings,
		keywords: [
			"configuração",
			"configuracao",
			"config",
			"settings",
			"numeração",
			"numeracao",
			"próximo número",
			"proximo numero",
			"série",
			"serie",
			"domínio",
			"dominio",
			"onvio",
			"integrações contábeis",
			"integracoes contabeis",
		],
	},
	{
		title: "Auditoria",
		url: "/auditoria",
		category: "Administração e sistema",
		icon: IconHistory,
		keywords: ["auditoria", "audit", "histórico", "historico", "logs"],
	},
	{
		title: "Ajuda",
		url: "/ajuda",
		category: "Administração e sistema",
		icon: IconHelp,
		keywords: ["ajuda", "help", "suporte", "documentação", "documentacao"],
	},
];
