// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  ajuda: dynamic(() => import("./Ajuda")),
  text_blcok: dynamic(() => import("./TextBlcok")),
};
