export const BANCOS_PADRAO = [
	{ codigo: "000", nome: "EM MÃOS" },
	{ codigo: "001", nome: "BANCO DO BRASIL S.A." },
	{ codigo: "003", nome: "BANCO DA AMAZÔNIA S.A." },
	{ codigo: "004", nome: "BANCO DO NORDESTE DO BRASIL S.A." },
	{ codigo: "021", nome: "BANESTES S.A. BANCO DO ESTADO DO ESPÍRITO SANTO" },
	{ codigo: "024", nome: "BANCO DE PERNAMBUCO S.A. - BANDEPE" },
	{ codigo: "025", nome: "BANCO ALFA S.A." },
	{ codigo: "027", nome: "BANCO DO ESTADO DE SANTA CATARINA S.A." },
	{ codigo: "029", nome: "BANCO BANERJ S.A." },
	{ codigo: "031", nome: "BANCO BEG S.A." },
	{ codigo: "033", nome: "BANCO SANTANDER S.A." },
	{ codigo: "036", nome: "BANCO BRADESCO BBI S.A." },
	{ codigo: "037", nome: "BANCO DO ESTADO DO PARÁ S.A." },
	{ codigo: "038", nome: "BANCO BANESTADO S.A." },
	{ codigo: "040", nome: "BANCO CARGILL S.A." },
	{ codigo: "041", nome: "BANCO DO ESTADO DO RIO GRANDE DO SUL S.A." },
	{ codigo: "044", nome: "BANCO BVA S.A." },
	{ codigo: "045", nome: "BANCO OPPORTUNITY S.A." },
	{ codigo: "047", nome: "BANCO DO ESTADO DE SERGIPE S.A." },
	{ codigo: "062", nome: "HIPERCARD BANCO MÚLTIPLO S.A." },
	{ codigo: "063", nome: "BANCO IBI S.A. BANCO MÚLTIPLO" },
	{ codigo: "065", nome: "BANCO LEMON S.A." },
	{ codigo: "069", nome: "BPN BRASIL BANCO MÚLTIPLO S.A." },
	{ codigo: "070", nome: "BRB - BANCO DE BRASÍLIA S.A." },
	{ codigo: "072", nome: "BANCO RURAL MAIS S.A." },
	{ codigo: "073", nome: "BB BANCO POPULAR DO BRASIL S.A." },
	{ codigo: "074", nome: "BANCO J. SAFRA S.A." },
	{
		codigo: "078",
		nome: "BES INVESTIMENTO DO BRASIL S.A.-BANCO DE INVESTIMENTO",
	},
	{
		codigo: "096",
		nome: "BANCO BM&F DE SERVIÇOS DE LIQUIDAÇÃO E CUSTÓDIA S.A",
	},
	{ codigo: "104", nome: "CAIXA ECONÔMICA FEDERAL" },
	{ codigo: "107", nome: "BANCO BBM S.A." },
	{ codigo: "116", nome: "BANCO TÉNICO S.A." },
	{ codigo: "151", nome: "BANCO NOSSA CAIXA S.A." },
	{ codigo: "175", nome: "BANCO FINASA S.A." },
	{ codigo: "184", nome: "BANCO ITAÚ BBA S.A." },
	{ codigo: "204", nome: "BANCO BRADESCO CARTÕES S.A." },
	{ codigo: "208", nome: "BANCO UBS PACTUAL S.A." },
	{ codigo: "214", nome: "BANCO DIBENS S.A." },
	{ codigo: "215", nome: "BANCO COMERCIAL E DE INVESTIMENTO SUDAMERIS S.A." },
	{ codigo: "217", nome: "BANCO JOHN DEERE S.A." },
	{ codigo: "222", nome: "BANCO CALYON BRASIL S.A." },
	{ codigo: "224", nome: "BANCO FIBRA S.A." },
	{ codigo: "225", nome: "BANCO BRASCAN S.A." },
	{ codigo: "229", nome: "BANCO CRUZEIRO DO SUL S.A." },
	{ codigo: "230", nome: "UNICARD BANCO MÚLTIPLO S.A." },
	{ codigo: "233", nome: "BANCO GE CAPITAL S.A." },
	{ codigo: "237", nome: "BANCO BRADESCO S.A." },
	{ codigo: "246", nome: "BANCO ABC BRASIL S.A." },
	{ codigo: "248", nome: "BANCO BOAVISTA INTERATLÂNTICO S.A." },
	{ codigo: "249", nome: "BANCO INVESTCRED UNIBANCO S.A." },
	{ codigo: "250", nome: "BANCO SCHAHIN S.A." },
	{ codigo: "252", nome: "BANCO FININVEST S.A." },
	{ codigo: "263", nome: "BANCO CACIQUE S.A." },
	{ codigo: "265", nome: "BANCO FATOR S.A." },
	{ codigo: "318", nome: "BANCO BMG S.A." },
	{ codigo: "320", nome: "BANCO INDUSTRIAL E COMERCIAL S.A." },
	{ codigo: "341", nome: "BANCO ITAÚ S.A." },
	{ codigo: "356", nome: "BANCO REAL S.A." },
	{ codigo: "366", nome: "BANCO SOCIETE GENERALE BRASIL S.A." },
	{ codigo: "370", nome: "BANCO WESTLB DO BRASIL S.A." },
	{ codigo: "376", nome: "BANCO J. P. MORGAN S.A." },
	{ codigo: "389", nome: "BANCO MERCANTIL DO BRASIL S.A." },
	{ codigo: "394", nome: "BANCO FINASA BMC S.A." },
	{ codigo: "399", nome: "HSBC BANK BRASIL S.A. - BANCO MÚLTIPLO" },
	{ codigo: "409", nome: "UNIBANCO - UNIÃO DE BANCOS BRASILEIROS S.A." },
	{ codigo: "422", nome: "BANCO SAFRA S.A." },
	{ codigo: "453", nome: "BANCO RURAL S.A." },
	{ codigo: "456", nome: "BANCO DE TOKYO-MITSUBISHI UFJ BRASIL S.A." },
	{ codigo: "464", nome: "BANCO SUMITOMO MITSUI BRASILEIRO S.A." },
	{ codigo: "477", nome: "CITIBANK N.A." },
	{ codigo: "479", nome: "BANCO ITAÚBANK S.A" },
	{ codigo: "487", nome: "DEUTSCHE BANK S.A. - BANCO ALEMÃO" },
	{ codigo: "488", nome: "JPMORGAN CHASE BANK" },
	{ codigo: "492", nome: "ING BANK N.V." },
	{ codigo: "505", nome: "BANCO CREDIT SUISSE (BRASIL) S.A." },
	{ codigo: "600", nome: "BANCO LUSO BRASILEIRO S.A." },
	{ codigo: "604", nome: "BANCO INDUSTRIAL DO BRASIL S.A." },
	{ codigo: "610", nome: "BANCO VR S.A." },
	{ codigo: "611", nome: "BANCO PAULISTA S.A." },
	{ codigo: "612", nome: "BANCO GUANABARA S.A." },
	{ codigo: "623", nome: "BANCO PANAMERICANO S.A." },
	{ codigo: "626", nome: "BANCO FICSA S.A." },
	{ codigo: "630", nome: "BANCO INTERCAP S.A." },
	{ codigo: "633", nome: "BANCO RENDIMENTO S.A." },
	{ codigo: "634", nome: "BANCO TRIÂNGULO S.A." },
	{ codigo: "637", nome: "BANCO SOFISA S.A." },
	{ codigo: "638", nome: "BANCO PROSPER S.A." },
	{ codigo: "641", nome: "BANCO ALVORADA S.A." },
	{ codigo: "643", nome: "BANCO PINE S.A." },
	{ codigo: "652", nome: "ITAÚ UNIBANCO BANCO MÚLTIPLO S.A." },
	{ codigo: "653", nome: "BANCO INDUSVAL S.A." },
	{ codigo: "655", nome: "BANCO VOTORANTIM S.A." },
	{ codigo: "707", nome: "BANCO DAYCOVAL S.A." },
	{ codigo: "719", nome: "BANIF-BANCO INTERNACIONAL DO FUNCHAL (BRASIL)S.A." },
	{ codigo: "734", nome: "BANCO GERDAU S.A." },
	{ codigo: "740", nome: "BANCO BARCLAYS S.A." },
	{ codigo: "745", nome: "BANCO CITIBANK S.A." },
	{ codigo: "746", nome: "BANCO MODAL S.A." },
	{ codigo: "747", nome: "BANCO RABOBANK INTERNATIONAL BRASIL S.A." },
	{ codigo: "748", nome: "BANCO COOPERATIVO SICREDI S.A." },
	{ codigo: "749", nome: "BANCO SIMPLES S.A." },
	{ codigo: "751", nome: "DRESDNER BANK BRASIL S.A. - BANCO MÚLTIPLO" },
	{ codigo: "752", nome: "BANCO BNP PARIBAS BRASIL S.A." },
	{ codigo: "755", nome: "BANCO MERRILL LYNCH DE INVESTIMENTOS S.A." },
	{ codigo: "756", nome: "BANCO COOPERATIVO DO BRASIL S.A. - BANCOOB" },
	{ codigo: "081-7", nome: "CONCÓRDIA BANCO S.A." },
	{ codigo: "M03", nome: "BANCO FIAT S.A." },
	{ codigo: "M06", nome: "BANCO DE LAGE LANDEN BRASIL S.A." },
	{ codigo: "M07", nome: "BANCO GMAC S.A." },
	{ codigo: "M08", nome: "BANCO CITICARD S.A." },
	{ codigo: "M09", nome: "BANCO ITAUCRED FINANCIAMENTOS S.A." },
	{ codigo: "M11", nome: "BANCO IBM S.A." },
	{ codigo: "M14", nome: "BANCO VOLKSWAGEN S.A." },
	{ codigo: "M16", nome: "BANCO RODOBENS S.A." },
	{ codigo: "M18", nome: "BANCO FORD S.A." },
	{ codigo: "M19", nome: "BANCO CNH CAPITAL S.A." },
	{ codigo: "M20", nome: "BANCO TOYOTA DO BRASIL S.A." },
	{ codigo: "M22", nome: "BANCO HONDA S.A." },
	{ codigo: "CARF", nome: "BANCO CARREFOUR S.A." },
	{ codigo: "ICRD", nome: "BANCO ITAUCARD S.A." },
	{ codigo: "BKPR", nome: "BANCO BANKPAR S.A." },
	{ codigo: "PRIN", nome: "BANCO PORTO REAL DE INVESTIMENTOS S.A." },
];

