import {
	bigint,
	char,
	date,
	foreignKey,
	index,
	numeric,
	pgTable,
	smallint,
	text,
	timestamp,
	varchar,
} from "drizzle-orm/pg-core";
import { cfop } from "./cfop.js";
import { motivorebaixa } from "./motivo-rebaixa.js";
import { ncm } from "./ncm.js";
import { notafiscal } from "./nota-fiscal.js";
import { produtos } from "./produtos.js";
import { unidademedida } from "./unidade-medida.js";
import { usuarios } from "./usuarios.js";

const numeric122 = numeric({ precision: 12, scale: 2, mode: "string" });
const numeric124 = numeric({ precision: 12, scale: 4, mode: "string" });
const numeric52 = numeric({ precision: 5, scale: 2, mode: "string" });
const numeric74 = numeric({ precision: 7, scale: 4, mode: "string" });
const numeric96 = numeric({ precision: 9, scale: 6, mode: "string" });
const numeric102 = numeric({ precision: 10, scale: 2, mode: "string" });
const numeric156 = numeric({ precision: 15, scale: 6, mode: "string" });
const numeric154 = numeric({ precision: 15, scale: 4, mode: "string" });
const numeric70 = numeric({ precision: 7, scale: 0, mode: "string" });

export const notafiscalitem = pgTable(
	"notafiscalitem",
	{
		id: text().primaryKey().notNull(),
		acrescimo: numeric122,
		acrescimofinanciamento: numeric122,
		acrescimosubtotal: numeric122,
		aliquotacofins: numeric124,
		aliquotacofinsincentivado: numeric122,
		aliquotacofinsretido: numeric52,
		aliquotafcpstanterior: numeric122,
		aliquotaicmsdesoneradosemdesc: numeric122,
		aliquotaicmsdiferencialentrada: numeric52,
		aliquotaicmsefetivo: numeric52,
		aliquotaicmsincentivado: numeric122,
		aliquotaicmspresumido: numeric52,
		aliquotaicmsstanterior: numeric122,
		aliquotaicmsstpresumido: numeric52,
		aliquotapis: numeric124,
		aliquotapiscofinssaidapreco: numeric52,
		aliquotapisincentivado: numeric122,
		aliquotapisretido: numeric52,
		aliquotareducaobasecalculoinss: numeric122,
		altura: numeric102,
		anofabricacao: smallint(),
		anomodelofabricacao: smallint(),
		aplicaprecocalculado: smallint(),
		basecalculoicmsdifal: numeric122,
		basecofins: numeric122,
		basecofinsretido: numeric122,
		basecontribuicaosocial: numeric122,
		basefcpinternonaoaproveitado: numeric122,
		basefcpstanterior: numeric122,
		basefundopobrezainterno: numeric122,
		basefundopobrezainternovirtual: numeric122,
		basefundopobrezast: numeric122,
		baseicms: numeric122,
		baseicmsconhecimento: numeric122,
		baseicmsdesoneradosemdesconto: numeric122,
		baseicmsdiferido: numeric122,
		baseicmsefetivo: numeric122,
		baseicmsnaoaproveitado: numeric122,
		baseicmspresumido: numeric122,
		baseicmsstanterior: numeric122,
		baseicmsstpresumido: numeric122,
		baseicmssubstituicao: numeric122,
		baseicmsvirtual: numeric122,
		baseimpostoaproximado: numeric122,
		baseimpostoimportacao: numeric122,
		baseimpostorenda: numeric122,
		baseinss: numeric122,
		baseipi: numeric122,
		baseiss: numeric122,
		basepis: numeric122,
		basepiscofinsconhecimento: numeric122,
		basepisretido: numeric122,
		basestufdestino: numeric122,
		brindeimportado: numeric52,
		cargatributariamedia: numeric122,
		cfop: varchar({ length: 20 }),
		chassi: varchar({ length: 17 }),
		chaveibpt: varchar({ length: 6 }),
		chavenfe: varchar({ length: 44 }),
		chavenferecebidaexportacao: varchar({ length: 44 }),
		cilindrada: varchar({ length: 4 }),
		classificacaofiscal: varchar({ length: 8 }),
		cm3: varchar({ length: 4 }),
		cmkg: varchar({ length: 9 }),
		cmvatual: numeric156,
		cnpjconcessionaria: varchar({ length: 18 }),
		cnpjemissor: varchar({ length: 14 }),
		codigobeneficiofiscal: varchar({ length: 10 }),
		codigolistalc11603: varchar({ length: 5 }),
		codigomarcamodelo: numeric70,
		cofins: numeric122,
		cofinsconhecimento: numeric122,
		cofinsretido: numeric122,
		comissao: numeric52,
		comissaoaprazo: numeric52,
		comissaoavista: numeric52,
		comissaopreco: numeric52,
		comissaoquitacao: numeric52,
		comprimento: numeric102,
		condicaoveiculo: smallint(),
		contador: smallint(),
		contribuicaosocial: numeric122,
		cor: varchar({ length: 4 }),
		cordenatran: varchar({ length: 2 }),
		cstcofins: varchar({ length: 2 }),
		cstpis: varchar({ length: 2 }),
		currenttimemillis: bigint({ mode: "number" }),
		custoadicional: numeric156,
		custoaquisicao: numeric156,
		customedio: numeric156,
		custooperacional: numeric122,
		custototal: numeric122,
		datahoraretirada: timestamp({ precision: 3, mode: "string" }),
		datalote: date(),
		dataprogramacaopreco: date(),
		decimaispreco: smallint(),
		decimaisquantidade: smallint(),
		deducaoicmsbasecofins: numeric122,
		deducaoicmsbasepis: numeric122,
		desconto: numeric122,
		descontoclienteprodutoaplicado: smallint(),
		descontofinanciamento: numeric122,
		descontopromocao: numeric122,
		descontosubtotal: numeric122,
		descricao: varchar({ length: 120 }),
		descricaoarma: varchar({ length: 256 }),
		descricaocor: varchar({ length: 40 }),
		despesasaduaneiras: numeric122,
		detalhenfe: text(),
		distanciaeixos: varchar({ length: 4 }),
		embalagem: numeric156,
		emissao: date(),
		entidadenotafiscalterceiros: varchar({ length: 60 }),
		enviartagsdiferimentototal: smallint(),
		especieveiculo: smallint(),
		fonteibpt: varchar({ length: 50 }),
		frete: numeric122,
		freteconhecimento: numeric122,
		freteoutrasdespesas: numeric122,
		funrural: numeric122,
		gerarcreditoicmsst: smallint(),
		gerarcreditoipi: smallint(),
		hash: bigint({ mode: "number" }),
		icms: numeric122,
		icmsconhecimento: numeric122,
		icmsdestino: numeric122,
		icmsdiferencialcomporpreco: numeric122,
		icmsdiferido: numeric122,
		icmsfcpinternonaoaprovaitado: numeric122,
		icmsfundopobreza: numeric122,
		icmsfundopobrezainterno: numeric122,
		icmsfundopobrezainternovirtual: numeric122,
		icmsfundopobrezast: numeric122,
		icmsnaoaproveitado: numeric122,
		icmsremetente: numeric122,
		icmsstinformadomanualmente: smallint(),
		icmssubstituicao: numeric122,
		icmsvirtual: numeric122,
		idajustedocumentofiscal: text(),
		idativoimobilizado: text(),
		idbasecalculocredito: text(),
		idbeneficiofiscal: text(),
		idcfop: text(),
		idcontribuicaosocialapurada: text(),
		idcontribuicaosocialapurcofins: text(),
		iddavitem: text(),
		iddevolucaoitem: text(),
		idembalagem: text(),
		idembalagemtributavel: text(),
		idenquadramentoipi: text(),
		identidadedesconto: text(),
		idestadoconcessionaria: text(),
		idfilialretiradaentrega: text(),
		idlote: text(),
		idmotivodesconto: text(),
		idmotivorebaixa: text(),
		idncm: text(),
		idnotafiscal: text().notNull(),
		idnotafiscalitemdevolvido: text(),
		idnotafiscalitemterceiros: text(),
		idnotafiscalitemtranscompra: text(),
		idnotafiscalitemtransfsaida: text(),
		idobservacaolancamentofiscal: text(),
		idpedidocompraitem: text(),
		idproduto: text(),
		idprodutobase: text(),
		idprodutokit: text(),
		idpromocao: text(),
		idreceitasemcontribuicao: text(),
		idrepresentante2: text(),
		idrequisicaotransferenciaitem: text(),
		idsupervisorvenda: text(),
		idtipocredito: text(),
		idunidademedida: text(),
		idunidademedidatributavel: text(),
		idusuariodesconto: text(),
		idusuarioretirada: text(),
		impostoaproximado: numeric122,
		impostoaproximadoestadual: numeric122,
		impostoaproximadofederal: numeric122,
		impostoaproximadomunicipal: numeric122,
		impostoimportacao: numeric122,
		impostorenda: numeric122,
		informacaoadicional: varchar({ length: 500 }),
		inss: numeric122,
		iof: numeric122,
		ipi: numeric122,
		ipinaodestacado: numeric122,
		iss: numeric122,
		itemorigempossuicofins: smallint(),
		itemorigempossuiicms: smallint(),
		itemorigempossuiipi: smallint(),
		itemorigempossuipis: smallint(),
		itempeps: smallint(),
		largura: numeric102,
		lotacao: smallint(),
		lote: varchar({ length: 30 }),
		lucrobruto: numeric122,
		marcaveiculo: varchar({ length: 20 }),
		margemvaloradicionado: numeric122,
		modalidadeicmsst: smallint(),
		modocalculoipi: smallint(),
		modocalculopreco: smallint(),
		motivodesoneracaocofins: smallint(),
		motivodesoneracaoicms: smallint(),
		motivodesoneracaoicmssemdesc: smallint(),
		motivodesoneracaopis: smallint(),
		naoconsiderarvalortotalnota: smallint(),
		naopossuiicmsstnotaorigem: smallint(),
		ncm: varchar({ length: 11 }),
		numerodrawback: varchar({ length: 20 }),
		numeroitempedidocompra: varchar({ length: 6 }),
		numeromotor: varchar({ length: 21 }),
		numeronotafiscal: varchar({ length: 11 }),
		numeronotafiscalterceiros: varchar({ length: 11 }),
		numeropedidocompra: varchar({ length: 15 }),
		numeroregistroexportacao: varchar({ length: 12 }),
		numeroseriearma: varchar({ length: 15 }),
		numeroseriecanoarma: varchar({ length: 15 }),
		observacao: varchar({ length: 20 }),
		observacaorebaixa: text(),
		origem: smallint(),
		outrasdespesas: numeric122,
		outrosimpostoscusto: numeric122,
		outrosimpostospreco: numeric122,
		outrosvalorescusto: numeric122,
		pautapreco: smallint(),
		perccontribuicaosocial: numeric52,
		percentualdesconto: numeric122,
		percentualfunrural: numeric52,
		percentualicms: numeric52,
		percentualicmsaproveitamento: numeric74,
		percentualicmsdestino: numeric52,
		percentualicmsdiferido: numeric74,
		percentualicmsfundopobreza: numeric52,
		percentualicmsfundopobrezast: numeric52,
		percentualicmsinterestadual: numeric52,
		percentualicmsnaoaproveitado: numeric52,
		percentualicmssubstituicao: numeric52,
		percentualicmsvirtual: numeric52,
		percentualipi: numeric124,
		percentualipinaodestacado: numeric124,
		percentualipisaida: numeric52,
		percentualiss: numeric74,
		percentuallucroajustado: numeric122,
		percentuallucromaximo: numeric122,
		percentuallucrominimo: numeric122,
		percentualmarkupajustado: numeric122,
		percentualmarkupcalculado: numeric122,
		percentualmercadoriadevolvida: numeric122,
		percentualoutrosvalorescusto: numeric122,
		percentualpartilhaicmsestados: numeric52,
		percentualprecominimovenda: numeric156,
		percentualredbaseicmsefetivo: numeric74,
		percentualreducaoicms: numeric96,
		percentualreducaoicmsdiferido: numeric52,
		percentualreducaoicmsnaoaprov: numeric52,
		percentualreducaoicmsvirtual: numeric96,
		percentualreducaoiss: numeric74,
		percentualreducaomva: numeric52,
		percentualretencaoiss: numeric74,
		percfcpinternonaoaproveitado: numeric122,
		percicmsdiferencialcomporpreco: numeric52,
		percicmsfundopobinternovirtual: numeric52,
		percicmsfundopobrezainterno: numeric52,
		percimpostoaproximado: numeric52,
		percimpostoaproximadoestadual: numeric52,
		percimpostoaproximadofederal: numeric52,
		percimpostoaproximadomunicipal: numeric52,
		percimpostorenda: numeric52,
		percinss: numeric52,
		percoutrosvalorespreco: numeric52,
		percredbasepiscofins: numeric52,
		percreducaoicmssubstituicao: numeric52,
		pesobrutoveiculo: varchar({ length: 9 }),
		pesoliquidoveiculo: varchar({ length: 9 }),
		pis: numeric122,
		pisconhecimento: numeric122,
		pisretido: numeric122,
		placaveiculo: varchar({ length: 8 }),
		pontoequilibrio: numeric156,
		potenciamotor: varchar({ length: 4 }),
		precificado: smallint(),
		precobruto: numeric122,
		precocusto: numeric156,
		precominimovenda: numeric122,
		precounitario: numeric156,
		precovendaajustado: numeric122,
		precovendaajustadopauta1: numeric122,
		precovendaajustadopauta2: numeric122,
		precovendaajustadopauta3: numeric122,
		precovendaajustadopauta4: numeric122,
		produto: varchar({ length: 20 }),
		produtoespecifico: smallint(),
		quantidade: numeric156,
		quantidadehora: varchar({ length: 5 }),
		quantidadepauta1: numeric156,
		quantidadepauta2: numeric156,
		quantidadepauta3: numeric156,
		quantidadepauta4: numeric156,
		quantidadepeca: bigint({ mode: "number" }),
		quantidadetributavel: numeric154,
		rebaixa: numeric156,
		referenciafornecedor: varchar({ length: 60 }),
		renavam: varchar({ length: 11 }),
		replicarcusto: smallint(),
		replicarformacao: smallint(),
		retencaoiss: numeric122,
		reterpiscofins: smallint(),
		retirado: smallint(),
		seguro: numeric122,
		serial: varchar({ length: 9 }),
		serie: varchar({ length: 4 }),
		situacaotributaria: varchar({ length: 3 }),
		situacaotributariadigitada: varchar({ length: 3 }),
		situacaotributariaipi: varchar({ length: 3 }),
		situacaotributariasn: varchar({ length: 3 }),
		statusprecoitem: smallint(),
		statusremessaterceiros: smallint(),
		taxasiscomex: numeric122,
		tipo: char({ length: 1 }),
		tipoarma: smallint(),
		tipocombustivel: varchar({ length: 8 }),
		tipodocumentopaf: varchar({ length: 1 }),
		tipokit: smallint(),
		tipooperacao: smallint(),
		tipopintura: varchar({ length: 1 }),
		tiporestricao: smallint(),
		tiporetiradaentregaitem: smallint(),
		tipotinta: smallint(),
		tipovalordesconto: smallint(),
		tipovaloricms: smallint(),
		tipovaloripi: smallint(),
		tipoveiculo: smallint(),
		total: numeric122,
		totalizadorparcial: varchar({ length: 10 }),
		tributacao: varchar({ length: 7 }),
		tributacaoespecial: varchar({ length: 7 }),
		unidade: varchar({ length: 6 }),
		unidademedidaxml: varchar({ length: 6 }),
		valorafrmm: numeric122,
		valorcofinsincentivado: numeric122,
		valordiferencaimportacaoxml: numeric122,
		valorfcpstanterior: numeric122,
		valoricmsaproveitamento: numeric122,
		valoricmsdesoneradosemdesconto: numeric122,
		valoricmsdiferencialentrada: numeric122,
		valoricmsefetivo: numeric122,
		valoricmsincentivado: numeric122,
		valoricmspresumido: numeric122,
		valoricmssaida: numeric122,
		valoricmsstanterior: numeric122,
		valoricmsstentrada: numeric122,
		valoricmsstpresumido: numeric122,
		valoricmssubstituto: numeric122,
		valorimpostosincentivados: numeric122,
		valorlancamentospedcusto: numeric122,
		valorlancamentospedcustodebito: numeric122,
		valoroutrosimpostoscusto: numeric122,
		valorpisincentivado: numeric122,
		valorstufdestino: numeric122,
		valorvendor: numeric122,
		veiculonovo: smallint(),
		vim: varchar({ length: 1 }),
	},
	(table) => [
		index("notafiscalitem_idnotafiscal_idx").using(
			"btree",
			table.idnotafiscal.asc().nullsLast().op("text_ops"),
		),
		index("notafiscalitem_idproduto_idx").using(
			"btree",
			table.idproduto.asc().nullsLast().op("text_ops"),
		),
		foreignKey({
			columns: [table.idnotafiscal],
			foreignColumns: [notafiscal.id],
			name: "fk_notafiscalitem_notafiscal",
		})
			.onUpdate("cascade")
			.onDelete("cascade"),
		foreignKey({
			columns: [table.idproduto],
			foreignColumns: [produtos.id],
			name: "fk_notafiscalitem_produto",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idprodutokit],
			foreignColumns: [produtos.id],
			name: "fk_notafiscalitem_produtokit",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idcfop],
			foreignColumns: [cfop.id],
			name: "fk_notafiscalitem_cfop",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idncm],
			foreignColumns: [ncm.id],
			name: "fk_nfitem_ncm",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idunidademedida],
			foreignColumns: [unidademedida.id],
			name: "fk_nfitem_unidademedida",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idunidademedidatributavel],
			foreignColumns: [unidademedida.id],
			name: "fk_nfitem_unidademedida_trib",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idmotivorebaixa],
			foreignColumns: [motivorebaixa.id],
			name: "fk_notafiscalitem_motrebaixa",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idusuariodesconto],
			foreignColumns: [usuarios.id],
			name: "fk_nfitem_usuariodesconto",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idsupervisorvenda],
			foreignColumns: [usuarios.id],
			name: "fk_nfitem_usuariopreco",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idusuarioretirada],
			foreignColumns: [usuarios.id],
			name: "fk_nfitem_usuario_retirada",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idnotafiscalitemterceiros],
			foreignColumns: [table.id],
			name: "fk_nfitem_nfi_terc",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idnotafiscalitemdevolvido],
			foreignColumns: [table.id],
			name: "fk_nfitem_nfi_dev",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
	],
);
