import { bigint, integer, pgTable, text, varchar } from "drizzle-orm/pg-core";

export const tipodocumentofinanceiro = pgTable("tipodocumentofinanceiro", {
	id: text().primaryKey().notNull(),
	descricao: varchar({ length: 50 }).notNull(),
	acao: integer().notNull(),
	saidafechamento: integer().default(0),
	inativo: integer().default(0),
	integracaixabanco: integer().default(0),
	baixageracodigobanco: integer().default(0),
	currenttimemillis: bigint({ mode: "number" }).notNull(),
	permitegerarboleto: integer(),
	idmotivobaixafinanceiro: text(),
	utilizadoemnegociao: integer(),
	enviamobile: integer(),
	tipousuario: integer().default(0),
	localusoboleto: integer().default(0),
	resgatarboleto: integer().default(0),
	calcularencargofinanceiro: integer(),
	juros: integer().default(0),
	multa: integer().default(0),
	descontoantecipacao: integer().default(0),
	desconsiderasabado: integer().default(0),
	desconsideradependente: integer().default(0),
	diasdeconsiderarjuros: integer().default(0),
	diasdeconsiderarmulta: integer().default(0),
	diasdesconsiderardesconto: integer().default(0),
	tipocalculojuros: integer(),
	consideraparainadimplencia: integer().default(0),
	enviaecommerce: integer(),
	formapagamentonfe: varchar(),
	tipocobrancasaas: integer(),
	codigomercos: integer(),
	idempresa: text().notNull(),
});
